### ISSUE TITLE
add locale independent questobjective detection

### ISSUE THREAD

**Issue by Lichery** [shagu/pfQuest#10]
I added in questParse this:
  ["ruRU"] = {
    [1] = "(.*) - убито",
  },
but 'slain' quests are not displayed on the map... What is the problem I do not understand. Maybe I forgot to add something somewhere. All quests of other types displayed correct

**Comment by shagu** [comment]
Great! Could you please send me a screenshot of those questobjectives?
(And please mark what the mob/item name is, and what the language suffix is)

Thanks in advance :)

**Comment by Lichery** [comment]
This "- убито:", I copied from ERR_QUEST_ADD_KILL_SII in GlobalStrings. Here can't be an error.

![bandicam 2017-10-20 20-17-22-610](https://user-images.githubusercontent.com/24303693/31833786-461a90f0-b5d4-11e7-8874-773d077b8041.jpg)

**Comment by shagu** [comment]
Wait WHAT?! There are globalstrings for that? This makes life much easier. :D

**Comment by Lichery** [comment]
loooool xD
[1.12.1 GlobalStrings.zip](https://github.com/shagu/pfQuest/files/1402892/1.12.1.GlobalStrings.zip)

**Comment by Lichery** [comment]
I'm sorry, I was wrong. Here is the correct line QUEST_MONSTERS_KILLED.
QUEST_MONSTERS_KILLED for QuestLog Frame
ERR_QUEST_ADD_KILL_SII  for UIErrors Frame

**Comment by shagu** [comment]
https://github.com/shagu/pfQuest/commit/3cd7fe0b9c28920fd86ef6e04863b4580c72a2c1
https://github.com/shagu/pfQuest/commit/01177f2eb2926336a1ad741a6082affe78ae7c20
