### ISSUE TITLE
minimap nodes break if the "Rotate Minimap" option is enabled

### ISSUE THREAD

**Issue by Artur91425** [shagu/pfQuest#107]
https://youtu.be/q_eCqxhpmzA

**Comment by shagu** [comment]
If anyone is interested, this part needs to get fixed: https://github.com/shagu/pfQuest/blob/master/map.lua#L803-L811

**Comment by Artur91425** [comment]
I looked at the implementation of this functionality in the QuestHelper and Gatherer addons. Both use the Astrolabe library. I don't have much time now to figure it out. Check it out, maybe you can find a solution there.
https://www.curseforge.com/wow/addons/astrolabe
https://www.dropbox.com/s/1n4tvooyin05h9x/Astrolabe.lua?dl=0 - 2.4.3. version
