### ISSUE TITLE
Database selection

### ISSUE THREAD

**Issue by Lichery** [shagu/pfQuest#11]
This addon has one big problem. It will only work if the client language and server localization language are the same. But I think you know that most servers only support enUS server localization. And if I want to play on a Russian client, on a server with enUS localization, then your addon will not work. :'(
Please implement the choice of the database language in the addon.

P.S. Sorry for my bad english...

**Comment by shagu** [comment]
Oh, I didn't knew that. I'm using the german and the english client. The server (elysium) always returned localized data for me. I assumed it would be the same for other languages, as all of those languages are available in their database.

**Comment by Lichery** [comment]
Of all 1.12 servers, only on Elysium was installed ruRU server localization. :)

**Comment by shagu** [comment]
A new download target has been added, called `noLoc`. Choose this if you are playing with a localized client (e.g ruRU) on a server that doesn't ship any translations (e.g kronos). The non-localized pfQuest download contains a complete enUS database plus the localized zone databases for every language.
