### ISSUE TITLE
TBC Bloodmyst Isle Quests

### ISSUE THREAD

**Issue by nonameform** [shagu/pfQuest#110]
While doing some questing on Bloodmyst Isle, I came across a Wanted Board that according to pfQuest is supposed to offer me _Wanted: 'Hogger'_ quest.

**Comment by nonameform** [comment]
Also there are plenty of chickens on Azuremyst Isle that are supposedly offer _CLUCK!_, however I believe only chicken in Westfall do that.

**Comment by shagu** [comment]
> Also there are plenty of chickens on Azuremyst Isle that are supposedly offer CLUCK!, however I believe only chicken in Westfall do that.

![image](https://user-images.githubusercontent.com/11586807/94372954-47237300-0102-11eb-9a85-f25952ef7cc6.png)

pfQuest-tbc reflects the state of the largest open source effort of wow emulation called cmangos. If your server behaves different for a reason, either get them contribute back from where they've taken from, or get it fixed on cmangos yourself. I will not make pfQuest aligned to any closed source private server.

> While doing some questing on Bloodmyst Isle, I came across a Wanted Board that according to pfQuest is supposed to offer me Wanted: 'Hogger' quest.

I can't find that one.

**Comment by nonameform** [comment]
![WoWScrnShot_092720_162002](https://user-images.githubusercontent.com/34381716/94373032-31ff1200-010b-11eb-88fa-acbae9592aa5.jpg)
That board is at Blood Watch.

**Comment by shagu** [comment]
Ah I see, it's tooltip only. There's no way to differeciate between mouseover's except for their title. I'd need to bring some more logic into.

**Comment by nonameform** [comment]
> pfQuest-tbc reflects the state of the largest open source effort of wow emulation called cmangos. If your server behaves different for a reason, either get them contribute back from where they've taken from, or get it fixed on cmangos yourself. I will not make pfQuest aligned to any closed source private server.

That is my bad actually. I believed that this quest only works with specific chickens in specific zons, but even in Vanilla days it worked with any chicken.

**Comment by shagu** [comment]
Tooltip fixed by https://github.com/shagu/pfQuest/commit/4830a007514a1367e0fb764cfcb14eabe930aa69
