### ISSUE TITLE
low FPS issue (TBC)

### ISSUE THREAD

**Issue by GioBego** [shagu/pfQuest#111]
game has extremely low FPS while there is too many points on the map (TBC client)

**Comment by shagu** [comment]
Do you have any addon running which collects addon-buttons on the minimap?

**Comment by GioBego** [comment]
yes, should this be relevant? ... when I disable tracking of quest with many points, FPS goes back to normal ... so it is only affected by amount of point in map it seems

**Comment by shagu** [comment]
Depending on which addon you use. Most of the addon button gather addons are not aware of pfQuest as it didn't exist when they were made. Therefore, some of them pick up the nodes of pfQuest and some of them can't handle that many objects on the minimap.

**Comment by GioBego** [comment]
Elv UI (version updated for TBC) and some included plugin for sorting the minimap buttons

**Comment by GioBego** [comment]
will removing button from minimap help ? will test it when FPS drops again

**Comment by shagu** [comment]
It's not about the minimap icon. It's about the nodes on the minimap.

**Comment by GioBego** [comment]
I will test if turning off minimap nodes helps. Thanks for your help.

p.s.: I would gladly use pfUI for TBC if it was compatible with Clique ... that is only reason I had to switch to ElvUI ... built in solution was not sufficient alternative to Clique

**Comment by shagu** [comment]
Add "pfMiniMapPin" to https://github.com/ElvUI-TBC/ElvUI_MinimapButtons/blob/master/ElvUI_MinimapButtons/ElvUI_MinimapButtons.lua#L247 to make it ignore the pfQuest icons.

> p.s.: I would gladly use pfUI for TBC if it was compatible with Clique ... that is only reason I had to switch to ElvUI ... built in solution was not sufficient alternative to Clique

What was missing?

**Comment by GioBego** [comment]
> What was missing?
ease of use(settings in spellbook with all options Clique has) , save separate settings for alts while using one profile for UI ... and support for alternative addons like Grid for example ... Clique is simply the standard everybody is used to ... I loved your ui had compatible Clique version for Vanilla

**Comment by shagu** [comment]
> I will test if turning off minimap nodes helps. Thanks for your help.

Try the latest version (5.2.6). The pfQuest minimap-nodes now mimic the names of Gatherer while a button collector is active, in order to not get grabbed by their algorithm. (<https://github.com/shagu/pfQuest/commit/31ed59ee770d8bf3f0708a1a5598e2fc4da9b21c>)

**Comment by shagu** [comment]
> p.s.: I would gladly use pfUI for TBC if it was compatible with Clique

There you go: https://github.com/shagu/pfUI/commit/fa966b99305f8172b76bfa151dfa8648922bfa2e, pfUI has clique support now.
