### ISSUE TITLE
quest path is not updated when changing zone

### ISSUE THREAD

**Issue by Artur91425** [shagu/pfQuest#113]
loaded only PfQuest 5.2.7
![Untitled](https://user-images.githubusercontent.com/24303693/95028258-b02d5c80-06a7-11eb-82b4-ec1a1b0ddf74.png)
![Untitled1](https://user-images.githubusercontent.com/24303693/95028261-b15e8980-06a7-11eb-9f19-7f8e1430128e.png)
![Untitled2](https://user-images.githubusercontent.com/24303693/95028262-b28fb680-06a7-11eb-87e4-4084de55d62f.png)

**Comment by shagu** [comment]
Thanks, fixed with 5.2.8 (https://github.com/shagu/pfQuest/commit/4b285f3935d6b2e36a9f75bc3f68e4ca5758be21)
