### ISSUE TITLE
[TBC] Destroy the Legion and Never Again!

### ISSUE THREAD

**Issue by nonameform** [shagu/pfQuest#115]
While questing in Ashenvale I have noticed that some mobs for _Destroy the Legion_ and _Never Again!_ quests will not have associated info in tooltip, even though when you kill them the kill count is updated properly.

Mobs in question are Mannoroc Lasher, Searing Infernal and Diathorus the Seeker. Not sure if it is pfQuest issue or has something to do with the server I play on (Karazhan). I have tried reloading UI, but that did not fix the problem.

**Comment by shagu** [comment]
Thanks, the tooltips for units that exist on several zones should be fixed by pfQuest 5.2.9 (https://github.com/shagu/pfQuest/commit/16ffa6fe66ce640367255d3671688ba19f50fb4e)
