### ISSUE TITLE
[Suggestion] Nodes/quests on world map.

### ISSUE THREAD

**Issue by QuadrozZz** [shagu/pfQuest#117]
Would be nice to make the option to show/hide quests/nodes on the Eastern Kingdoms, Kalimdor, Azeroth, Outland. That means for watch completed quests as visual, on the full map when planning your way. Like it doing que%^e addon.
example : https://wow.zamimg.com/uploads/blog/images/16458-wow-classic-addon-spotlight-questie.png
please

**Comment by journeym** [comment]
Would be great. At least for Turtle, on Turtle questie is not an option

**Comment by QuadrozZz** [comment]
Three years have passed. So sadly it is still didn't released.
