### ISSUE TITLE
How to disable mob tooltips?

### ISSUE THREAD

**Issue by necropresto** [shagu/pfQuest#118]
Is there any way to disable mobs extended tooltips?

![screenshot](https://user-images.githubusercontent.com/1387160/98140816-a7959500-1ea4-11eb-9753-180988064af1.png)

**Comment by shagu** [comment]
A new option has been added in https://github.com/shagu/pfQuest/commit/d54f5d2b1243fdff9c38381072b875ae801e6c0e (Release 5.3.1) called "Show Tooltips"
