### ISSUE TITLE
Not registering quest conclusion with "hide quests"

### ISSUE THREAD

**Issue by necropresto** [shagu/pfQuest#119]
Quest conclusion are not being registered if "hide quests" is choose in map drop-down menu.

To replicate:

- Create new char
- Choose "Hide quests" in world map drop-down menu
- Complete some quests
- Choose "Show quests" in world map drop-down menu
- You see quests you just completed as not completed

**Comment by shagu** [comment]
Quest-completion is now tracked independent to the drop-down selection. Also the readme has been adjusted to reflect the differences of "Manual Mode" and "Hidden" Mode. https://github.com/shagu/pfQuest/commit/e6b7c7fdccffed0623615d509f218b0a4d93dbf3 (Release 5.3.1)
