### ISSUE TITLE
Tracked Quests - Question

### ISSUE THREAD

**Issue by Road-block** [shagu/pfQuest#12]
When the Tracked Quests option is selected for showing Quest POI on the map.  
Is it intended that completing the Quest (which if tracked, un-tracks it) should remove the POIs for that quest?  
This is not the current behavior as far as I can tell.  
Quest objective POIs and questgiver POIs remain and have to be cleared manually if the quest becomes untracked due to completion. 😃

**Comment by shagu** [comment]
https://github.com/shagu/pfQuest/commit/5a3cb17040589bd2db386a0e4fda09f6bf939870
