### ISSUE TITLE
Minimap nodes disappear

### ISSUE THREAD

**Issue by Artur91425** [shagu/pfQuest#121]
Loaded only pfQuest (latest as of 18.11.2020)
1) Stand so that there is a quest icon on the minimap (tested with new quest icon (yellow exclamation mark))
2) Open WorldMap
3) Open any **other location** with available quests and they will be displayed on the world map
4) Hover the mouse over any node
5) Close the world map (the bug is not affected by whether the mouse over is on the node at the time of closing)
6) Minimap nodes disappear :-)

P.S. It is important to complete point 3. If you hover the mouse over the nodes in the current location, there is no bug.
P.P.S If necessary, I can record a video.

**Comment by shagu** [comment]
Thanks for your report, should be fixed by https://github.com/shagu/pfQuest/commit/3c6347f23e8922b3c9f4bdfcd065449b366fd642
