### ISSUE TITLE
clusters and nodes decrease on the world map

### ISSUE THREAD

**Issue by Artur91425** [shagu/pfQuest#122]
Loaded only pfQuest (latest as of 22.11.2020)

1. Open WorldMap
2. Hover your mouseover any node (bug only for exclamation and question icons) or cluster. In other words, a bug only for those objects that increase with mouse hover.
3. Left-click on the hovered object.

Suggestion: rebuild the path to the quest, on the nodes or cluster of which the left mouse button was clicked (I mean the first path, which is light green). The idea is that, if desired, the player can rigidly indicate and lock the path to a specific quest, ignoring any nearby quests that come across on the way.

**Comment by shagu** [comment]
https://github.com/shagu/pfQuest/commit/2c2dac72172755c7b7fecb3d287a068255d02ca5

> Suggestion: rebuild the path to the quest, on the nodes or cluster of which the left mouse button was clicked (I mean the first path, which is light green). The idea is that, if desired, the player can rigidly indicate and lock the path to a specific quest, ignoring any nearby quests that come across on the way.

Maybe another time.
