### ISSUE TITLE
Weird behavior after last updates

### ISSUE THREAD

**Issue by nonameform** [shagu/pfQuest#126]
At first it seemed that there was an issue with the quests in DB, but after some time I have discovered that it is an issue in pfQuest.

![WoWScrnShot_120820_122424](https://user-images.githubusercontent.com/34381716/101479568-71e04200-3963-11eb-89b5-48cfc2905258.jpg)

On this screenshot I am hovering over the mob at the center of the image. As you can see he has a silver question mark over his head. However, pfQuest draws a golden question mark on the minimap and in the tooltip you can see that I am ready to turn in _The Admiral's Orders_. 

![WoWScrnShot_120820_122427](https://user-images.githubusercontent.com/34381716/101479674-9cca9600-3963-11eb-8d41-91f4f60f5542.jpg)

You can see on the second screenshot that pfQuest believes that I am on that quest as it tells me to turn it in to the NPC.

![WoWScrnShot_120820_122433](https://user-images.githubusercontent.com/34381716/101479729-b8ce3780-3963-11eb-843a-ef43753de353.jpg)

In my questlog I have the next quest in that chain that requires me to travel to Orgrimmar.

Then I have encountered the same problem with the quest _Call of Flame_, that requires me to travel to the Barrens and speak to NPC.

![WoWScrnShot_120820_142533](https://user-images.githubusercontent.com/34381716/101479872-ea470300-3963-11eb-96ef-6b531238d169.jpg)

However, pfQuest believes that I do not have that quest as demonstrated by golden exclamation mark where a question mark should be. pfQuest also believes that I am already on the next quest in the chain.

![WoWScrnShot_120820_142545](https://user-images.githubusercontent.com/34381716/101479906-fe8b0000-3963-11eb-961f-ef15f9f4c65f.jpg)

But once I move into the Barrens...

![WoWScrnShot_120820_142920](https://user-images.githubusercontent.com/34381716/101480049-2ed29e80-3964-11eb-9224-036e38963b25.jpg)

Apparently there is an issue with pfQuest when it comes to quests that take you to another zone.

**Comment by shagu** [comment]
Did you disable the quest-log buttons? Because if not, it would mean that the quest wasn't identified properly by pfQuest.
Is this Vanilla or TBC?

**Comment by nonameform** [comment]
Vanilla, buttons are disabled. It is only true for quests that have the same title. For example, _Ride to Orgrimmar_ shows correctly that I have to go to Org.

**Comment by Muehe** [comment]
Similar problem as #109 it seems.

Glancing at the code for a minute, checking the [Objectives](https://github.com/cmangos/issues/wiki/Quest_template#objectives) field in addition to the title should take care of a lot of those ambiguities, and the ones mentioned here in particular. There are still some edge cases which have exactly the same title and objectives text, but a lot less and most of them are exclusive to each other or for different races anyway.

**Comment by shagu** [comment]
I don't think it's a wrong detection of the quest. The quest detection is quite good since it checks for titles, objectives, texts, races, professions and in addition using levenshtein to find the best if there are still doubts.

It's more likely to be a missing update to the questgiver symbols after completing the previous quest.

@nonameform If you have something like that next time, could you please open the map, select "Hide Quests" and then "All Quests" in the dropdown menu, this would update all nodes and would tell us if it's a repaint issue or not.

**Comment by shagu** [comment]
> Before submitting the issue I did reload the UI and even logged out of the game. As I found out later, for whatever reason pfQuest did not register that I have completed the previous quest in The Admiral's Orders chain.

Thanks, this information helps a lot. :+1:

**Comment by shagu** [comment]
Do you use any addons for quick quest turn in and auto accept new quests?

**Comment by nonameform** [comment]
Nope.

At the time I made this post I was running the following addons:

aux - AH addon
BetterCharacterStats - makes stats display in the similar to TBC fashion
Mail - mailbox addon
Outfitter - character outfit manager
SP_SwingTimer - melee swing timer
pfUI
pfQuest

**Comment by shagu** [comment]
I wish I could help here. I tried several times, but I'm unable to reproduce it:

[![Youtube](https://img.youtube.com/vi/vI8O8i_VT4g/0.jpg)](https://youtu.be/vI8O8i_VT4g)

**Comment by nonameform** [comment]
Look at what I have got for you.

Here I am standing at Durotar, minding my own business before moving into Orgrimmar.

![WoWScrnShot_120920_153745](https://user-images.githubusercontent.com/34381716/101631059-d0292580-3a34-11eb-9cd5-dc0c72d31d6b.jpg)

Then this happens.

![WoWScrnShot_120920_153751](https://user-images.githubusercontent.com/34381716/101631112-e636e600-3a34-11eb-955d-6d86829bfb6a.jpg)

If I enable questlog buttons, it works correctly and only shows the quest in Durotar when I press _Show_.

**Comment by nonameform** [comment]
I realized that the second time I had this issue it was the same story as with _The Admiral's Orders_: for whatever reason pfQuest did not register that I have already turned in previous _Call of Fire_ quest. So once I changed zone to Org, it showed me a golden exclamation mark above an NPC. It is still weird, since I never had that issue before and I have been running pfQuest since Kronos 3 started, so over 2 years now.

**Comment by nonameform** [comment]
I have encountered the same issue (but on a different PC) at Teldrassil with _Crown of the Earth_ questline. After I have picked up [the last quest in chain](https://classicdb.ch/?quest=935), pfQuest showed me that the NPC which gave me the quest also has some other quest from the same chain available for pick up.

I am surprised that I am the only person with that problem, yet it happens on different PCs :(

**Comment by shagu** [comment]
Did this happen while using the latest `6.2.2` version? Do you have any kind of "compatibility" addons running that could mess around in the Addon-API?

Since the Jan 7, 2021 there is an idle-updater that should automatically check for quest changes that haven't been painted yet and trigger a map refresh if one is found.

**Comment by nonameform** [comment]
Yes, I used the latest version of pfQuest. I am running a very minimal addon setup and all addons are compatible with 1.12, no weird stuff.

I wonder if any leftover settings from previous versions might cause that issue for me.

**Comment by shagu** [comment]
> I wonder if any leftover settings from previous versions might cause that issue for me.

There's no config changes that could produce that. If you ever had another character with the same name on the same realm previously, your quest journal could still include completed quests from the previous character. You could check `/db journal` for completed quests and verify. While questing, if you type `/db debug` you will see the internal actions whenever pfQuests refreshes either the quest givers or the quest nodes. This would at least give some trace when something happens again.

**Comment by shagu** [comment]
>  I am running a very minimal addon setup and all addons are compatible with 1.12

I'm not talking about incompatible addons here, it's more like addons called `!Compatibility` and similar, that turn the 1.12 API into some weird state somewhere between 1.12 and 3.3.5a, overwrite functions, change the return values, and and and.

**Comment by nonameform** [comment]
> While questing, if you type `/db debug` you will see the internal actions whenever pfQuests refreshes either the quest givers or the quest nodes. This would at least give some trace when something happens again.

I will try that.

> I'm not talking about incompatible addons here, it's more like addons called `!Compatibility` and similar, that turn the 1.12 API into some weird state somewhere between 1.12 and 3.3.5a, overwrite functions, change the return values, and and and.

Nope, nothing like that.

The list is almost the same as in December:

aux - AH addon
BetterCharacterStats - makes stats display in the similar to TBC fashion
Mail - mailbox addon
Outfitter - character outfit manager
pfUI
pfQuest
YaHT - hunter timer addon
