### ISSUE TITLE
The newly created level 1 role does not accept any task times error.

### ISSUE THREAD

**Issue by aixiu** [shagu/pfQuest#14]
pfquest just created a role in the absence of any task when the error situation.
This situation only exists in the role of a time when no task is being given, that is, when the game into the game, there is an infinite error situation, as long as the task is not finished

pfquest+EQL3 Will appear 
![kyj avlmh1g w2en vstid](https://user-images.githubusercontent.com/8064012/31858164-47d0ee94-b723-11e7-8256-ae2d0bf2f6ea.jpg)
Two alone are not wrong

**Comment by aixiu** [comment]
![default](https://user-images.githubusercontent.com/8064012/31858176-e1a69622-b723-11e7-8505-b3d212bf876b.png)

**Comment by aixiu** [comment]
![default](https://user-images.githubusercontent.com/8064012/31858186-1d598508-b724-11e7-97b7-b8fc052d5f75.png)
There is no task when the error

**Comment by Lichery** [comment]
This error occurs because of #11

**Comment by shagu** [comment]
That's an EQL3 issue and unrelated to pfQuest.

**Comment by Cephel** [comment]
See also: https://github.com/laytya/EQL3/issues/4

**Comment by aixiu** [comment]
@ Cephel  thx.
