### ISSUE TITLE
Incorrect droprate (Bug)

### ISSUE THREAD

**Issue by Mistymimi** [shagu/pfQuest#144]
For many items the drop rate listed isn't reflective of the server's droprate. Since most vanilla servers use vmangos maybe it could be updated to those values? There are so many items that I don't think its realistic to go item by item but maybe there's a way to easily automate adjusting these listed droprates?

**Comment by shagu** [comment]
As you can see in the addon description, it already uses the VMaNGOS database for vanilla. 
> The vanilla version is powered by the database of VMaNGOS. The Burning Crusade version is using data from the CMaNGOS project with translations taken from MaNGOS Extras.

The pfQuest database was last updated to the latest VMaNGOS state at: 30 Jul 2021.

If you say there was a massive change in droprates since then, please list at least a few examples.

**Comment by Mistymimi** [comment]
I guess some servers I thought were using vmangos must be using something else possibly cmangos or trinitycore.
