### ISSUE TITLE
Add-On does not show up in WoW

### ISSUE THREAD

**Issue by felan09** [shagu/pfQuest#15]
Simple, issue for me...this add-on does not show up in the add-on listing in 1.12.1. I've renamed the downloaded file to pfQuest

**Comment by shagu** [comment]
![1](https://camo.githubusercontent.com/9b0bc4d84087059db8251000ac921ad5868c903e/68747470733a2f2f692e696d6775722e636f6d2f516473576844632e706e67)

**Comment by felan09** [comment]
thx for your reply..works now like a charm:)
