### ISSUE TITLE
 quest id:  356, quest ender not showing on map and tracker

### ISSUE THREAD

**Issue by stephanelol** [shagu/pfQuest#151]
quest id:  356 is not showing up the quest ender mark on map, Display current quest givers and include quest enders both set to check

**Comment by shagu** [comment]
Works for me:
![Screenshot from 2022-08-07 11-52-13](https://user-images.githubusercontent.com/11586807/183285322-1fcdc428-154e-4478-9b72-a4ced970fc4b.png)
