### ISSUE TITLE
Game freezes in cold-boot (no wdb) when loading with many quests

### ISSUE THREAD

**Issue by CAKyPA** [shagu/pfQuest#158]
Hi,
Noticed that TWoW client freezes when loading with many quests that have a many nodes.
It loads fine without pfQuest addon.

To replicate this issue make a non Undead horde character, level up to 15.
Then go to Tirisfal Glades and pick the all available quests in Brill and Undead starting zone.
Also if the character is mage pick the Gathering Materials (Linen Cloth) quest for more nodes.
With this map would be full of nodes.
Now exit the game (not logout) and try to load the game.

Found 2 ways to load the game.
1. Disable pfQuest > Enter the game > Logout > Enable pfQuest > Game loads fine.
2. Just wait, it may take 1 or more minutes to unfreeze.

It's like when game loads, pfQuest trying to calculate all the nodes, routes at one time that game can't handle.
To fix this add a slow loading at start.
Also I'm using the TWoW client without WDB folder as they advised.

**Comment by shagu** [comment]
Hi, Thanks for your report. Do you by any chance use EQL3? Did you tried those steps while pfQuest was the only addon?
Because, as you close the game it could also by a WDB cache thing that the game freezes, no matter of pfQuest.
I had such issues previously with EQL3, that used API calls that require WDB cache (or server response which takes to long) and because freezes on cold-boot. To narrow it down further, it would help me if you could verify that cold-boots work **with** an WDB folder, but freeze **without**?

**Comment by CAKyPA** [comment]
> Do you by any chance use EQL3?

No, currently using:
* Bagnon
* Bagnon_Core
* Looking For Turtles
* PvP Warning
* pfQuest
* pfQuest Icons
* pfQuest TWoW DB
* ShaguWidget
* ShaguTweak
* ShaguPlates (currently disabled)

> Did you tried those steps while pfQuest was the only addon?

No, just tried enabling/disabling pfQuest, pfQuest Icons, pfQuest TWoW DB.

> Cold-boots work with an WDB folder, but freeze without?

Currently game cold-boots fine with or without a WDB folder, maybe because I'm already did the Tirisfal Glades quests.
Will try to replicate this when I had a similar situation with many quests with many nodes.

As for WDB trick I'm using, "delete the WDB folder then create the empty file named WDB without extension".

**Comment by CAKyPA** [comment]
Found a same game freezing situation in Durotar.
Made a Goblin character > Did all starting zone quests > Picked all the quests in Razor Hill > Went to Valley of Trials and did all the quests > Then went to Sen'Jin Village and picked all the quests > At this time I've got around 15 active quests with full of nodes in map > Game freezes in cold boot.

First, tried enabling WDB folder.
Enabled WDB folder (currently empty) > Cold boot > Game freezes > Disabled pfQuest > Game loads fine > Exit game > Game creates cache files in WDB folder > Enabled pfQuest > Game loads fine.

So as you suggested problem was in a WDB folder.
If the WDB folder is empty and you have many quests, there's a chance to game freezes in cold boot.

Also game loads fine with only "questcache.wdb" file in WDB folder.

**Comment by khoopek** [comment]
happens to me too but not on cold boot.
if i have more than 12/13 quests, whenever the quest updates (either by increasing counter or completing task), game will freeze for a second.
happened after i've updated pfquest to the latest version 3 days ago.
