### ISSUE TITLE
Tracking goes away after killing a mob related to a tracked quest

### ISSUE THREAD

**Issue by Cephel** [shagu/pfQuest#16]
Basically when you display the locations of NPCs related to a quest, then kill one of the quest NPCs, the minimap and map display of NPCs disappears.

Used in conjunction with EQL3
Map mode set to "Manual Selection"

**Comment by shagu** [comment]
https://github.com/shagu/pfQuest/commit/5a3cb17040589bd2db386a0e4fda09f6bf939870
