### ISSUE TITLE
fps suddenly crawled to a halt

### ISSUE THREAD

**Issue by maybedisp** [shagu/pfQuest#161]
![WoWScrnShot_092922_223919_proc](https://user-images.githubusercontent.com/114700006/193139466-5c4395e0-c98f-4544-963d-299596df40e4.jpg)

Everything was working normally, then i picked up another quest and my fps tanked from locked 120 down to ~15 and chat got filled with pfquest lua errors. I've already tried using the "delete everything" option in pfquest, and i still can't get it back to a working state.  Also, both pfquest and pfquest-turtle is up to date

What do?

**Comment by maybedisp** [comment]
![WoWScrnShot_092922_230110_proc](https://user-images.githubusercontent.com/114700006/193141470-f4bfa308-05f7-4ef5-97cf-874f5590f76f.jpg)
This is my settings if that matters.

**Comment by shagu** [comment]
Fixed by https://github.com/shagu/pfQuest/commit/f335e33de12d433668d7da99e477c2f6a9ccd51d
Version will be 6.7.4

**Comment by shagu** [comment]
Do you remember the name of the quest that made this happen?

**Comment by maybedisp** [comment]
Yeah, it's the quest I'm standing in front of.
Red Skies of Durotar

**Comment by WarMEN3** [comment]
Same problem with the griffin quest in Elvinforest.
I decided this way: in the map.lua file I added **or "X"** at the end of line 434
```lua
  meta["description"] = pfDatabase:BuildQuestDescription(meta)

  local addon = meta["addon"] or "PFDB"
  local map = meta["zone"]
  local coords = meta["x"] .. "|" .. meta["y"]
  local title = meta["title"]
  local layer = GetLayerByTexture(meta["texture"])
  local spawn = meta["spawn"] or "X"
  local item = meta["item"]

  local sindex = string.format("%s:%s:%s:%s:%s:%s", addon, map, coords, title, layer, spawn, item)

```
