### ISSUE TITLE
Freezing, Disconnecting when loading/reloging between characters

### ISSUE THREAD

**Issue by Deprot80** [shagu/pfQuest#179]
I'm getting a lot of disconnects since i started using pfquest. It almost always happens when i relog to another character and the loading bar is almost 100% i get dc. More people said they're experiencing the same thing on 1.12 client.

**Comment by shagu** [comment]
Probably the same as here: https://github.com/shagu/pfQuest/issues/158
I wasn't ever able to reproduce it.
