### ISSUE TITLE
[TBC][Minimap][Strata][Addon Conflict] Handynotes

### ISSUE THREAD

**Issue by Sattva-108** [shagu/pfQuest#184]
## Description
In **TBC 2.4.3** **pfQuest** seems to have **lower strata** than **Handynotes** addon icons on **minimap.** 
**Map strata** of pfQuest is good!
## Link
**Link** to Handynotes addon: 
https://www.wowace.com/projects/handynotes/files/132303
## How to reproduce
**Steps:**

1. Install **pfQuest-tbc**
2. Install **Handynotes**
3. Find some available quest nearby
4. Create note and drag it over quest _**(guide for it below).**_
5. You should see its over **pfQuest minimap icon**

**To create new note in Handynotes do the following steps:**

1. Open world map
2. **Alt-Right click** somewhere empty on map (not on the quest)
3. Click Okay (to create note)
4. **Mouseover** just made note
5. **Shift+Ctrl+Lefclick** to drag.

## Some Screenshots
**How it looks on minimap**

![Wow_ext_nameplates_gVUT6uuxR6](https://user-images.githubusercontent.com/74269253/224853877-391a9b2f-259a-4ba7-b403-f923ab8ca960.png)

**How it looks on world map**

![Wow_ext_nameplates_QJKnYZkU8j](https://user-images.githubusercontent.com/74269253/224853940-1e667dd7-cc36-4af6-8948-d125b88144d2.png)

**Comment by Sattva-108** [comment]
## I also found this bug with player arrow strata

This part of code doesn't work for WorldMapFrame. (However it works for Minimap:GetChildren )
![sublime_text_kuAiFi95hF](https://user-images.githubusercontent.com/74269253/225762350-1241106c-b857-45af-b76b-3d1d7ceeaf3f.png)

It looks like this on my World Map frame. Can't find myself.
![firefox_49iTGMYqkJ](https://user-images.githubusercontent.com/74269253/225762487-59e9d557-3512-4e72-b2c3-894d9c6e3666.png)

**Comment by shagu** [comment]
I'm not very active in wow right now, and don't play on a TBC server at all at the moment. So it might take some while till i get to it. 

It looks like the player position frame strata solution was made for 1.12 and before 2.4.3 support was ready. Guess I'll need to figure out a way on how to do it in 2.4.3.

Regarding the frame stratas in gerneral, I'm not yet sure what to do here. I assume there will be always an addon that put its stuff above, and maybe someone else prefers to have his handynotes above the pfQuest icons like it is right now.
I'll think about it. But in general I dislike the idea to regulary scan all minimap and worldmap nodes for the highest strata and then automatically adjust mine above.

I can't yet tell how it ends, but as you brought it to my attention, I'll promise that next time I play TBC, i won't be able to **not** see it and must do something about it :laughing:
