### ISSUE TITLE
Minimap Mouseover doesn't work

### ISSUE THREAD

**Issue by Manixer** [shagu/pfQuest#19]
Hey Shagu,

I just discovered your successor of shaguquest and directly downloaded it (Version 1.3)!
Unfortunately the display of the tooltips in the minimap doesn't work and there isn't an error code.
I disabled all other addons and even tried it on another client where I never had any addons installed.

Quick update: the previous version works flawlessly!

Hope you can help =)

Tahlia

PS: Spielst du nicht mehr auf Nefarian? Hab dich mal im Discord geaddet (Manix) ;)

**Comment by shagu** [comment]
Fixed on pfQuest `master` and pfUI `master`.

PS: Ne, nichtmehr.
