### ISSUE TITLE
Quest indicator no longer appears on nameplates / unit frames

### ISSUE THREAD

**Issue by tippfelher** [shagu/pfQuest#193]
The targeted enemy is a quest mob but has no "loot" symbol on nameplate / unit frame. How can I fix this?

(unsure whether this is a bug or I misconfigured something :x)

Edit: https://imgur.com/a/IDOBiYN

Thanks

**Comment by shagu** [comment]
pfQuest never had that feature

**Comment by Hiethen** [comment]
> pfQuest never had that feature

Coming when?

**Comment by shagu** [comment]
No plans
