### ISSUE TITLE
Turtle WoW - Quest: [2] Package for Thurman - wrong coords

### ISSUE THREAD

**Issue by wezlol** [shagu/pfQuest#194]
![image](https://github.com/shagu/pfQuest/assets/35075726/e55d82c7-5c9f-4de0-9512-697de0bf5d1b)
----
![image](https://github.com/shagu/pfQuest/assets/35075726/76b5b3fc-3783-4ab9-98a9-f7f086c7c5df)
Correct coords: 42.4 83.3
https://www.wowhead.com/classic/npc=1429/thurman-schneider

**Comment by shagu** [comment]
Please always use the latest versions of both pfQuest and pfQuest-turtle before reporting issues.
It appears to be at the correct locations with the latest version:
![Screenshot from 2023-05-29 10-43-41](https://github.com/shagu/pfQuest/assets/11586807/bbe10ed5-a5a3-44c5-90ce-bddd93171454)
