### ISSUE TITLE
Completed quests still showing up, don't get hidden automatically

### ISSUE THREAD

**Issue by harrypotterIUP** [shagu/pfQuest#198]
I'm on WoW 1.12.1 with most recent pfQuest 6.8.8.

First of all, thank you very much for this addon. It's proven to be very helpful. :heart:

However, I experience the following issue: All quests that I have already completed so far still show up on the map. Only newly completed quests since installing pfQuest disappear automatically. This is very tedious because obviously I don't remember every single quest from the past so I don't know which ones I can safely manually hide because I already completed them.

Is pfQuest not able to automatically hide past completed quests?

**Comment by shagu** [comment]
Sadly, pfQuest is not able to do this. An API call to query the server for completed quest was introduced during Wotlk and is not available in 1.12 and 2.4.3.
