### ISSUE TITLE
[1.12] /db taxi

### ISSUE THREAD

**Issue by jendryk** [shagu/pfQuest#199]
/db taxi command shows stable master instead of flight masters

**Comment by shagu** [comment]
I just tried it, works fine for me:
![Screenshot from 2023-06-11 15-56-44](https://github.com/shagu/pfQuest/assets/11586807/b28574d0-3e44-4cc1-bac3-f63dc6e0d9bf)

**Comment by jendryk** [comment]
Are these Flight masters or Stable Masters? Most of these are share locations so it might be misleading.

**Comment by shagu** [comment]
Yes, as the tooltip tells, those are the following flight masters:
- Devrak <Wind Rider Master> (https://classicdb.ch/?npc=3615)
- Omusa Thunderhorn <Wind Rider Master> https://classicdb.ch/?npc=10378
- Bragok <Flight Master> https://classicdb.ch/?npc=16227
- Shardi <Wind Rider Master> https://classicdb.ch/?npc=11899

**Comment by jendryk** [comment]
![obraz](https://github.com/shagu/pfQuest/assets/7814954/c60e812c-eee2-41fb-80d2-6a6edd9f85de)
This is what shows when I use /db taxi

**Comment by shagu** [comment]
Was an issue in pfQuest-turtle, not pfQuest. Fixed in latest pfQuest-turtle via https://github.com/shagu/pfQuest-turtle/commit/7b07f9fa85d01c7176a9683aab9e1db6b90ab797

In future, if you have troubles on Turtle-Wow, please use the correct bugtracker or at least mention it.

**Comment by jendryk** [comment]
Sure, sorry 😅
