### ISSUE TITLE
Initial file loading improvement

### ISSUE THREAD

**Issue by Road-block** [shagu/pfQuest#2]
One minor thing if you are using a script to package the different language versions.  
It might be worth it to have it comment out other locale database files from the .toc when packaging a single locale release.  
The reason is for cutting down on game loading times (a little bit).  
The game scans for files referenced in the .toc file and takes the time to make error entries in Logs\FrameXML.log etc, it's not significant but every little bit helps 😃

**Comment by shagu** [comment]
Would anyone really notice the difference? Initially I had it like that, but as I didn't noticed anything, I removed it again while cleaning up the makefile

**Comment by Road-block** [comment]
Only people on toasters and if they have a bunch of addons I guess. 😝   
Most of this stuff is undetectable nowadays for people on SSDs, some extra HDD read/writes won't be perceptible by a human.
