### ISSUE TITLE
Add Comments from WHDB into quests in questlog

### ISSUE THREAD

**Issue by moootv** [shagu/pfQuest#20]
If using WHDB you can see comments from back then below the quest descriptions. Possible to add them?

**Comment by Lichery** [comment]
These comments are not taken from the site, they are all written as a database in the addon if file qData.lua
I do not think that it will be problematic to add them, but what is the point?

**Comment by moootv** [comment]
There are quests where comments are very handy, e.g. the Silithus Combat Mission Quests - comments give good suggestions, where to go, what to do, which order etc. Stuff pfquest, questie etc. doesn't tell you.

**Comment by shagu** [comment]
Nope. I won't do that. 
I'd like to keep all pfQuest databases autogenerated from the latest server databases and I'm not very motivated to cross-translate qData.lua into all other languages.
