### ISSUE TITLE
Minimap button not showing

### ISSUE THREAD

**Issue by exp0sed** [shagu/pfQuest#208]
Hi there,

I accidentally removed the minimap button. I've re-downloaded the addon and cleared all my wtf folders of pfQuest on all my accounts and characters and the minimap button is still missing.

Any help would be appreciated.

Thank you!

**Comment by shagu** [comment]
Hi, you can type: `/db config` to open the settings menu, there you can enable `Enable Minimap Button` again.

**Comment by exp0sed** [comment]
Hi Shagu,

I've tried this many times and for some reason on a specific character it will not show up on my minimap button.
Are there any other options to troubleshoot this issue?

Thank you sir!

**Comment by shagu** [comment]
Maybe it went offscreen. Try to lower your UI Scale in the video settings and see if it appears somewhere.

**Comment by exp0sed** [comment]
Update: I fixed the issue. User must go to wtf>account>(acc-name)>(server)>(char-name) then click "layout-cache", then search for "pfBrowserIcon" & change the x,y coordinates. 

Thank you
