### ISSUE TITLE
/db spawn Iron ore does not work

### ISSUE THREAD

**Issue by moootv** [shagu/pfQuest#21]
/db spawn Iron ore
or
/pfdb spawn Iron ore

or any other search always results in "No machtes".

**Comment by shagu** [comment]
http://db.vanillagaming.org/?item=2772#mined-from-object
"Iron Ore" is an item. "Iron Deposit" is the spawned gameobject.

**Comment by moootv** [comment]
Update your description please
https://github.com/shagu/pfQuest
