### ISSUE TITLE
Quest: Assisting the Children of the Sun

### ISSUE THREAD

**Issue by khoopek** [shagu/pfQuest#210]
Wrong type of "action" in the pfQuest arrow tracking:
![image](https://github.com/shagu/pfQuest/assets/110908179/2a4d2fa9-6336-493c-9c51-6f93814092e8)

Quest says to speak to the NPC instead of killing...
![image](https://github.com/shagu/pfQuest/assets/110908179/01eef590-9a2c-4427-901a-4972dffcc6b6)

**Comment by shagu** [comment]
Should now be fixed via: https://github.com/shagu/pfQuest/commit/c47fb77d4b706e276765b36da57f209fb62dc924
