### ISSUE TITLE
ERROR attempt to index field 'buttonOnline'(a nul value)

### ISSUE THREAD

**Issue by Zoobug** [shagu/pfQuest#215]
Installed the newest version of pfQuest + pfQuest Turtle and when I launch the game, open quest log and click on a quest i get spammed with the error.

ERROR: Interface\Addons\pfquest\quest.lua,613: attempt to index field 'buttonOnline'(a nil value)

I copied the download from an old version and im not getting the error. Do you know what's causing it only with newest version?

**Comment by shagu** [comment]
I don't know, I've never seen that error and I don't get the error.

**Comment by quinnb1994** [comment]
I had a similar error and reloaded turtle wow, and it fixed itself. But upon reloading I noticed that the ui didn't originally change and now it has and there is no error.

**Comment by Zoobug** [comment]
I reinstalled new version not getting the error now. It looked like it was conflicting with another addon not able to pin down which one however I am still getting conflicts between Aux and Cooldowns. So probably one of them I will close the bug as it's not an issue with the addon.
