### ISSUE TITLE
How can i cycle through the maps which include a search result?

### ISSUE THREAD

**Issue by moootv** [shagu/pfQuest#22]
E.g. i search for "Large Venom Sac" and several zones have mobs which drop them, how can i cycle through the zones?

**Comment by shagu** [comment]
You can't. Any suggestions/screenshots where to place such a button? :)

**Comment by moootv** [comment]
Each click on the sword icon could work as the cycle function - or place it next to the sword icon. I would suggest to keep it simple and just use the sword icon.
https://gyazo.com/f35fedf55952dfc4ea7110b103b43378

**Comment by Lichery** [comment]
but it seems to me better to add two arrows next to the sword sign

**Comment by Lichery** [comment]
something like this
![f35fedf55952dfc4ea7110b103b43378](https://user-images.githubusercontent.com/24303693/32161235-d99b2a18-bd65-11e7-8c7c-1f620a567fb1.jpg)

**Comment by moootv** [comment]
the sword icon becomes unnecessary clutter then. If so, remove the sword icon.

**Comment by Lichery** [comment]
The sword icon shows what this item dropping from the mobs. Move mouse over it and you will see the list.

**Comment by Lichery** [comment]
You can make it so that when you hover over the sword icon, all mobs in zone A are shown, and when you click on the sword, the list of mobs for zone B would be displayed, and so on.

**Comment by Lichery** [comment]
I think it will be perfect. But in this case it will be necessary to do something like a hint for the players, in which it would be written that pressing the sword makes a transition between the zones.

**Comment by moootv** [comment]
No pressure, but are you still going to implement it, @shagu ?

**Comment by shagu** [comment]
Haven't started yet

**Comment by Muehe** [comment]
I feel this problem would better be solved by showing notes on the continent/world maps or at least highlighting zones which have active nodes in them.

**Comment by shagu** [comment]
In my opinion, this creates too much effort, ui-clutter and ressource load for a feature with only a little benefit, as the UI already shows you a list of all zones including their spawn counts.

Me for myself, I'm not going to add this. Feel free to convince me with a nice and clean Pull Request that doesn't unnecessarily clutters the UI and won't affect the performance. :wink:
