### ISSUE TITLE
All quests appears in the pfQuest tracker

### ISSUE THREAD

**Issue by Hydra9268** [shagu/pfQuest#222]
I created an alt, and this is happening. All quests automatically appear in the tracker when I am in the quest's zone, regardless of whether the quest is being tracked in the Quest Log. The pfQuest menu doesn't have anything I can do to correct this.

![BF0JqioAi7](https://github.com/shagu/pfQuest/assets/932134/fe1ce70e-73f5-4970-a1f7-0a07b1f8ca57)

There's way too much stuff appearing on the map, and it gets worse as more quests get added.

![UWJa4yddkd](https://github.com/shagu/pfQuest/assets/932134/e9660b62-2166-4a6d-96c0-c0b5569dc637)

This issue doesn't happen to my main character.

**Comment by shagu** [comment]
On there World Map is a drop down menu, which is set to "All Quests" in your screenshot. 
Set it to "Tracked" to only see quests that you track.

**Comment by Hydra9268** [comment]
Yup, that was it. Thank you!
