### ISSUE TITLE
Love Song for Narain

### ISSUE THREAD

**Issue by Artur91425** [shagu/pfQuest#229]
https://www.wowhead.com/classic/quest=8599

The quest is not displayed because it is indicated that it has a pre-quest https://www.wowhead.com/classic/quest=8597, but this is not true. Quest `8599` can only be obtained together with `8597`, but not after completing `8597`.

In this comment https://github.com/shagu/pfQuest/pull/221#issuecomment-1827860263  you had a very good idea with the `overwrites.lua` file as a temporary solution to database problems. Please add this file for further filling with database corrections.

**Comment by Artur91425** [comment]
I also ask you to write the database architecture with a brief description at the beginning of file `overwrites.lua`

**Comment by shagu** [comment]
> I also ask you to write the database architecture with a brief description at the beginning of file `overwrites.lua`

Hi, there's an overwrites file via: https://github.com/shagu/pfQuest/commit/20141b1da12101ca72e45a9297efc05742becdf5
