### ISSUE TITLE
conflict: MBF (Minimap Button Frame)

### ISSUE THREAD

**Issue by tsheeley** [shagu/pfQuest#23]
You know what... while writing this, literally just now, I figured out the problem. It's Minimap Button Frame. I disabled all my map mods and the Ogre nodes were the proper size. Then turned just MBF on again... they're huge. (see the screenshots below so this all makes sense. ha.)

I guess you can close this out right away then. That way it's at least archived if someone else ends up having the same problem. I'll also note the thread too.

*****

Per your request... here is a screenshot of my minimap showing the overly large icons.

![image](https://user-images.githubusercontent.com/31299310/32307443-a968ef68-bf3d-11e7-94b4-e60da78748e4.png)

The large icons you see are for "An Unwelcome Guest", "Solomon's Law", "Howling in the Hills", and "Shadow Magic". 

I was able to recreate the "floating" off the map issue I mentioned on the forum, but only until I moved far enough that the icon disappeared from the minimap normally. Once I did that, they were properly dropping off the map instead of floating about an inch or so away.

For the map mod addons... I'm using Questie, Atlas, Cartographer, Gatherer, Minimap Button Frame, RecipeRadar, and of course pfUI.

Here's a shot of of the "Mo'grosh Ogre" nodes for the "Mercenaries" quest. You see the extra space in Minimap Button Frame... that's only there when the nodes are active on the minimap.

![image](https://user-images.githubusercontent.com/31299310/32308091-32225bb6-bf41-11e7-8112-6a5e25720009.png)

Another shot of the same area, but fully zoomed in... there are less invisible buttons on MBF now.

![image](https://user-images.githubusercontent.com/31299310/32308170-ae8090e2-bf41-11e7-9238-17abb441abba.png)

*** Added this to show you after MBF is turned off. Same area, still fully zoomed. Guess I need to find a new button container.

![image](https://user-images.githubusercontent.com/31299310/32308588-e3fe2c96-bf43-11e7-8093-f38851640c77.png)

**Comment by Lichery** [comment]
![bandicam 2017-11-14 23-34-02-580](https://user-images.githubusercontent.com/24303693/32803532-da2b9c98-c994-11e7-8bd0-52f9e4e1246f.jpg)

This bug was due to the fact that the addon perceived notes as buttons of other addons. To fix it, just add "pfMiniMapPin" to the list MinimapIcons:
MinimapButtonFrame.lua
76 line:
local MinimapIcons = { "Note", "JQuest", "Naut_", "MinimapIcon", "GatherMatePin", "WestPointer", "Chinchilla_", "SmartMinimapZoom","QuestieNote", "smm", "pfMiniMapPin" };

**Comment by shagu** [comment]
Thanks, I'll do a PullRequest tomorrow

**Comment by Lichery** [comment]
PullRequest was merged

**Comment by shagu** [comment]
Oh, Thanks alot @Lichery
