### ISSUE TITLE
Suggestion: Convert Map-Size Units to Meters

### ISSUE THREAD

**Issue by Vorgrim** [shagu/pfQuest#233]
in File locales.lua

Someone forget to add this variable in this file (this for RU sections):
	["Quest Tracker Unfold Objectives"] = "Квест-трекер разворачивать цели",
	["Quest Objective Icons (Mini Map)"] = "Значки целей квеста (мини-карта)",
	["Quest Objective Icons (World Map)"] = "Значки целей квеста (карта-мира)",
	["Quest Objective Spawn Points (Mini Map)"] = "Точки появления цели квеста (мини-карта)",
	["Quest Objective Spawn Points (World Map)"] = "Точки появления цели квеста (карта-мира)",
	["Use Monochrome Cluster Icons"] = "Монохромный кластер значков",
	**["meters"] = " метров",**	--New variable. Many people prefer the metric number system

in File route.lua

string 430:	local distance = floor(target[4]*10)/10	--change to:
	local distance = floor(target[4]*10)/**0.9144**	--0.9144 meters in yard

string 432:	this.distance:SetText("|cffaaaaaa" .. pfQuest_Loc["Distance"] .. ": "..string.format("%.1f", distance))	--change to:
	this.distance:SetText("|cffaaaaaa" .. pfQuest_Loc["Distance"] .. ": "..string.format(**"%d "**, distance) **.. pfQuest_Loc["meters"]** )

P.S. Please teach the addon to sort quests by lvl, by distance to objects, by locations, and other conditions in the quest tracker :-)

**Comment by shagu** [comment]
Hi,

I don't think it's yards at all. It is using the map coordinates (where each map is 0-100 in both axis). Are you sure each map is exactly 100 yards in both axis?

**Comment by Vorgrim** [comment]
If you believe the TomTom addon from other patches of the game, then in yards. If you measure the distance by eye, you get 2 steps of the arch = 1.5 meters approximately. A normal human step is approximately 0.7 meters

**Comment by shagu** [comment]
Don't they use astrolabe which contains real sizes for each map? Haven't looked into it for a while.

**Comment by Vorgrim** [comment]
I'm sorry, I don't understand what you're talking about. The astrolabe?

**Comment by shagu** [comment]
Astrolabe is a map Library that many other addons use, which contains all kind of map-conversions.

**Comment by Vorgrim** [comment]
I think, i understand you)) Then value 0.9144 just need to multiply by the map scale
If you dive so deep into it, then you will need to calculate the distance taking into account the height of the character))))
Height depends on the character's race and gender :-)
0,9144 - This value can be tailored to each race of each gender depending on height. The higher the character, the greater the value

**Comment by Vorgrim** [comment]
Sorry, a mistake. This value cannot be the size of a single character step, because then the same distance for each race will be different
