### ISSUE TITLE
Fix locales

### ISSUE THREAD

**Issue by Vorgrim** [shagu/pfQuest#236]
Hi)) In file "**locales.lua**" need add this code in ruRU section:

["Quest Tracker Unfold Objectives"] = "Квест-трекер разворачивать цели",
["Quest Objective Icons (Mini Map)"] = "Значки целей квеста (мини-карта)",
["Quest Objective Icons (World Map)"] = "Значки целей квеста (карта-мира)",
["Quest Objective Spawn Points (Mini Map)"] = "Точки появления цели квеста (мини-карта)",
["Quest Objective Spawn Points (World Map)"] = "Точки появления цели квеста (карта-мира)",
["Use Monochrome Cluster Icons"] = "Монохромный кластер значков",
![WoWScrnShot_050124_184826](https://github.com/shagu/pfQuest/assets/165318772/e059d15d-7917-4cc3-ac57-9da3ec4ecb6c)

**Comment by shagu** [comment]
Thanks! I haven't updated the locale tables for a long time.
I will generate new ones and include your changes with it today :)

**Comment by shagu** [comment]
Translation tables updated via: https://github.com/shagu/pfQuest/commit/23d744f86a54afa0a510ea0a10bf7b5a623dfd6e

Your translations added via: https://github.com/shagu/pfQuest/commit/703498d5dcda230d8d45b1d198ccf935f6dcd107
