### ISSUE TITLE
Conflict with latest version of !Questie

### ISSUE THREAD

**Issue by AriinPHD** [shagu/pfQuest#24]
pfQuest does no longer run alongside !Questie. pfQuest causes !Questie to put up a permanent "error" pop-up that does not go away when you click the ok button (so I assume it's being spammed over and over).

Is this something you have time to look at? Latest !Questie is in beta still... link: https://github.com/AeroScripts/QuestieDev/releases

Thanks!

**Comment by shagu** [comment]
Please tell me the Error.

**Comment by AriinPHD** [comment]
Sorry for lazying it, here's a screenshot:
![wowscrnshot_110517_001325](https://user-images.githubusercontent.com/5846389/32410366-765d51c6-c1be-11e7-949b-f38f0c6842eb.png)

**Comment by shagu** [comment]
Ah, I see, they check for the existance of pfUI (in order to enable squared minimap support) in a "bad" way. I'll make a Pull Request to Questie tomorrow.

**Comment by shagu** [comment]
You could try a quickfix by running:
`/run pfUI_config["disabled"] = { ["minimap"] = "1" }`

**Comment by shagu** [comment]
https://github.com/AeroScripts/QuestieDev/pull/463

**Comment by shagu** [comment]
https://github.com/shagu/pfQuest/commit/3b449babd68840d8ff8baa7c34e9078fdd0bd947

**Comment by shagu** [comment]
Thanks for your report. A Pull Request has been sent to Questie and a workaround has been introduced in pfQuest which will be available in the next release build.
