### ISSUE TITLE
Suggestion : option to show quests below your level 

### ISSUE THREAD

**Issue by buhfur** [shagu/pfQuest#240]
My reasoning for this feature is due to turtle wow. Players may still earn experience from grey quests. This would allow players to view the lower level quests so they may pick them up and complete them later.

**Comment by b-chance** [comment]
Buhfur, the option is already there: check pfQuest Config (ingame)
![image](https://github.com/user-attachments/assets/70f5a5cc-23a9-4178-aac9-2ff2c1706f75)

**Comment by Bennylavaa** [comment]
This could be closed it already exists :p.
