### ISSUE TITLE
3.3.5 Map Error

### ISSUE THREAD

**Issue by Bennylavaa** [shagu/pfQuest#243]
make your map small like this using the down arrow thing in the top right corner of the map use reloadui or log out and back in then go to your quest log and click the show button the client freaks out. I am using elvui here but it happens using the default blizzard ui. Keep in mind if you opened the small map and make it visible prior to clicking show it works as youd expect.

![image](https://github.com/user-attachments/assets/69d2252a-888e-44b5-8c44-47ac01918264)
![image](https://github.com/user-attachments/assets/ab38b441-95d5-4e27-967a-ea04148d3092)

**Comment by shagu** [comment]
I'm unable to reproduce that on wotlk with only pfQuest loaded

**Comment by Bennylavaa** [comment]
Weird I can reproduce it on the latest build with no other addons enabled. 

https://www.loom.com/share/f7d2080eae5d4c0ea7e8b1375efaea44

**Comment by shagu** [comment]
[Screencast_20240926_181938.webm](https://github.com/user-attachments/assets/84b16b75-6925-4c62-add0-0c1f259c8735)

**Comment by Bennylavaa** [comment]
@shagu I notice your map isnt showing the quest tracker inside of it like most 3.3.5 servers. 

<img width="1257" alt="Screenshot 2024-09-26 at 12 24 41 PM" src="https://github.com/user-attachments/assets/20ee0a8f-bc44-4a7f-b3a0-24d5343f1a3f">

What server are you testing on?

**Comment by shagu** [comment]
Note: For future reference, here's the UI-Code that throws the error:
https://github.com/Gethe/wow-ui-source/blob/3.3.5/FrameXML/WorldMapFrame.lua#L747-L751

I don't know why `:GetCenter()` returns `nil` for you but not for me. pfQuest doesn't hook the `WorldMapButton_OnUpdate` function and it also doesn't change the position of it.

**Comment by shagu** [comment]
> @shagu I notice your map isnt showing the quest tracker inside of it like most 3.3.5 servers.
> <img alt="Screenshot 2024-09-26 at 12 24 41 PM" width="1257" src="https://private-user-images.githubusercontent.com/165105701/371234343-20ee0a8f-bc44-4a7f-b3a0-24d5343f1a3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNjg1MzMsIm5iZiI6MTcyNzM2ODIzMywicGF0aCI6Ii8xNjUxMDU3MDEvMzcxMjM0MzQzLTIwZWUwYThmLWJjNDQtNGE3Zi1iM2EwLTI0ZDUzNDNmMWEzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNlQxNjMwMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOGMyNzI1YzhkYWRhNWE1YzgxZjZjMTIxNDA2NmY0ZWFkNDhlMjFiMTViNjgzYWEzNGFjNWYyOTVmMWE0ZDk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZDnDyYtdUo5WWpCvCn7T-_JrVJsEj5ciN1raDInnX6g">
> 
> What server are you testing on? I wonder if this could be why?

Rising-Gods. But it doesn't matter if I enable it or not. I tried it several times with and without the objectives.
It's also not a server setting, it's the checkbox at the worldmap that you are referring to:

![image](https://github.com/user-attachments/assets/11d1524f-9625-44d9-bedc-e37a75cc8282)

**Comment by shagu** [comment]
The client I use is `enGB`, but also tried on `deDE` with the following build informations: 
![image](https://github.com/user-attachments/assets/d2549ec4-b0dd-48a1-823e-01b048cd8621)

**Comment by Bennylavaa** [comment]
![image](https://github.com/user-attachments/assets/4355ed74-46fe-4fa2-979e-f595135b7e82)
Mine is `enUS` and that is the only difference.

**Comment by Bennylavaa** [comment]
just some more info ive downloaded a fresh chromiecraft client with all default settings and it has the same issue. So I downloaded a enGB client from https://wowdl.net/client/World-of-Warcraft-3.3.5a.12340 and I have the same issue with that as well so I guess we wait to see if someone else can reproduce this as well.
