### ISSUE TITLE
vanilla KR client issue

### ISSUE THREAD

**Issue by samahee** [shagu/pfQuest#246]
i'm using vanilla KR client(1.12.1).
Naturally, all area names are displayed in Korean. However, when I use an addon, the quest icons do not show up at all.
Refer to the image below.
<img width="672" alt="pfquest01" src="https://github.com/user-attachments/assets/ad8540bb-d1c2-4e9c-a459-5ecc426d0ff2">

The interesting thing is that by modifying the WoW MPQ data to change all area names to English, I can see them.
Refer to the image below.
<img width="558" alt="pfquest02" src="https://github.com/user-attachments/assets/dd50f20b-3487-4dfe-9250-a937c504b56f">

Both images above are the latest versions.

In the pfQuest version 2.1.2, icons are visible on the map.
<img width="520" alt="pfquest03" src="https://github.com/user-attachments/assets/3c4d42c6-ec41-4e0f-b15d-091aa1009f37">

There were no error messages or logs.

**Comment by samahee** [comment]
I checked the source and figured out why it wasn’t working.
Issue closed.

**Comment by crackion** [comment]
samahee, What specific package did you modify? I have the same problem, but worse, with my Spanish client.

**Comment by samahee** [comment]
> samahee, What specific package did you modify? I have the same problem, but worse, with my Spanish client.
I changed db/koKR/zones.lua file
Check the zone names used in the Spanish client.

**Comment by crackion** [comment]
> > samahee, What specific package did you modify? I have the same problem, but worse, with my Spanish client.
> > I changed db/koKR/zones.lua file
> > Check the zone names used in the Spanish client.

Thank you, I apreciate it too much
