### ISSUE TITLE
Cartographer - nodes and tooltips

### ISSUE THREAD

**Issue by Mkmk93** [shagu/pfQuest#25]
First, thanks for all your great work with pfUI and pfQuest.

With pfQuest Beta 2.0 I finally replace questie because I love the look of pfQuest more and also the included Database.

Now I discovered two bugs when using Cartographer (r18701). 

1. "World Map Node Transparency" has no effect on the world map in Cartographer (always no transparency).
2. The tooltip of nodes in Cartographer are not in the front. So when you have a lot of pfQuest nodes, it displays the nodes in the foreground.

[Screenshot](https://imgur.com/a/wZEyY)

**Comment by Mkmk93** [comment]
Addition:

There are moments where both bugs don't appear after some time. When I search in the db for a mob and let me show the position, all the nodes get the correct transparancy until I close the map again. After   playing with the Clean and Reset button, the tooltip on the map is now displayed in the front.

**Comment by shagu** [comment]
Looks more like a cartographer issue for me.

**Comment by Muehe** [comment]
This is indeed a Cartographer issue, I had that fixed in my ShaguQuest fork. You can download it [from here](https://github.com/Muehe/classicdb/releases) (the Cartographer includes some other bug fixes and additions).
