### ISSUE TITLE
Almost never works when searched for a NPC.

### ISSUE THREAD

**Issue by sercant** [shagu/pfQuest#26]
![image](https://user-images.githubusercontent.com/6319501/32689885-493ab2ce-c6f5-11e7-9419-fba66294f5fa.png)

When I search for an NPC and click on it I get this error.

```
## Interface: 11200
## Title: |cff33ffccpf|cffffffffQuest
## Author: Shagu
## Notes: A lightweight Questhelper and Database
## Version: 2.0beta
## OptionalDeps: pfUI
## SavedVariablesPerCharacter: pfQuest_config, pfDatabase_fav, pfQuest_history, pfQuest_colors
```

OS: MacOSX

**Comment by shagu** [comment]
Which version is that?

**Comment by sercant** [comment]
I included the top of the .toc file in the message and it looks like Version: 2.0beta. I am using Cartographer as map addon. But not using pfUI. When I search a mob using the pfQuest GUI and click on the result gives me this error.

**Comment by shagu** [comment]
Did you've downloaded a Release or using the `master` ? Because both are labeled as `2.0beta`.

**Comment by sercant** [comment]
It's the release version

**Comment by shagu** [comment]
Version 2.0beta (enUS), active addons: `pfQuest`, `Cartographer`
* Search for "Kodo" in Browser ("Mobs & Objects")
* Click on `Teal Kodo`
* Click on `Kodo Calf`
* Click on `Kodo Bull`

=> No Error.

**Comment by sercant** [comment]
I will make a video when I can reproduce it.

**Comment by shagu** [comment]
https://github.com/shagu/pfQuest/commit/ed53a833b0841a3b740422a121c5b9d5cca7de09

**Comment by sercant** [comment]
Glad I was helpful to solve it. It was appearing after some time of gameplay in one session. Trying right after the login i didn't get the error.

**Comment by shagu** [comment]
You had another addon or macro which created a variable called "func". This one was picked up by pfQuest and throwed the error.
