### ISSUE TITLE
locale independent objective parser

### ISSUE THREAD

**Issue by Lichery** [shagu/pfQuest#27]
just tested and noticed a bug:
This is due to #11. 
Parser doesn't work I checked it on my server with ruRU game client and enUS server database.
Accordingly in the addon I use the base enUS(look at screenshot). After clicking on the Show button, no marks appear on the minimap:
![bandicam 2017-11-12 22-11-40-265](https://user-images.githubusercontent.com/24303693/32702330-8b8742f8-c7f6-11e7-879e-4a8479b9e87c.jpg)

P.S. if use the same locales in the server and the client, then the parser works correctly.

**Comment by shagu** [comment]
Add ruRU locales to your server if you want to use a russian client.

**Comment by Lichery** [comment]
I reproduced the situation described in #11. If the players play on their client, and the server will not return text for the locale of their client (ENUS text will return), then in your addon this parser will not work.

**Comment by Lichery** [comment]
I signed from below that if the languages of the client and server are the same, then everything works. But if suddenly the server does not return the client's locale data(return enUS data), then the parser does not work

**Comment by shagu** [comment]
It's unrelated to the parser and is related to: https://github.com/shagu/pfQuest/issues/11

**Comment by Lichery** [comment]
why unrelated with the parser? It is the parser that does not work under certain conditions:
server locale = locale addon databases ≠ game client locale 

 I wrote in the first message: "Accordingly in the addon I use the base enUS(look at screenshot)". So it turns out that I reproduced the conditions written above and the parser did not work.

**Comment by shagu** [comment]
> why unrelated with the parser?

Because it's the zones.lua, the parser itself is working. You can't see anything on your map, because the zones.lua in enUS only contains enUS maps, which leads to the fact that no nodes are displayed because a valid zone can not be opened.

**Comment by Lichery** [comment]
Exactly, I completely forgot about the zones... Thank you.
