### ISSUE TITLE
Need a way to synchronize between two systems

### ISSUE THREAD

**Issue by Sadiboy** [shagu/pfQuest#28]
as stated above, im sometimes playin on my homecomputer and sometimes on my laptop. so if i create a character on my home pc, play it some time and decide to continue on my laptop, pfquest on my laptop still thinks he is a fresh character and doesnt recognize what i have already done.

**Comment by Lichery** [comment]
looool...
Copy this file to your laptop:
WoW directory\WTF\Account\ACCOUNT_NAME\SERVER_NAME\PLAYER_NAME\SavedVariables\pfQuest.lua

**Comment by shagu** [comment]
You could either play TBC where players are able to query the server for completed quests, or you start using a network share for your SavedVariables. As I don't know much about Windows, I can't tell you how you could achieve a working setup for that.
