### ISSUE TITLE
browser: replace quest-text wildcards in tooltip

### ISSUE THREAD

**Issue by Lichery** [shagu/pfQuest#29]
add handling $ character: 
$N - UnitName("player")
$C - strlower(UnitClass("player"))
$R - strlower(UnitRace("player"))
$B - \n
$G - gender
I always did the following processing:
For example:
string = $GText1:Text2;
replace: "..gsub(gsub(UnitSex("player"), "^2$", "Text1"), "^3$", "Text2").."
![bandicam 2017-11-17 20-11-32-503](https://user-images.githubusercontent.com/24303693/32959746-b35896d4-cbd3-11e7-83bc-b061c75823de.jpg)

**Comment by shagu** [comment]
Gimme a list of all wildcards and their meaning and I'll add them

**Comment by Lichery** [comment]
I just updated the description and wrote where to make any substitutions.

**Comment by shagu** [comment]
Thanks :)

**Comment by Lichery** [comment]
Update
$C and $R must be in lower case. In quests they are always written small.
$C - strlower(UnitClass("player"))
$R - strlower(UnitRace("player"))
