### ISSUE TITLE
1.2.2: Error on icon's right click

### ISSUE THREAD

**Issue by byaka** [shagu/pfQuest#3]
```
ERROR: Interface\AddOns\pfQuest\pfBrowser.lua:393: attempt to index global `pfQuestConfig' (a nil value)
```

**Comment by shagu** [comment]
Works for me.
- Make sure to restart the game after an upgrade.
- Make sure to use the release version:
![1](https://i.imgur.com/QdsWhDc.png)

**Comment by byaka** [comment]
ofc im use release version...

**Comment by shagu** [comment]
please run `/run pfQuestConfig:Show()`

**Comment by byaka** [comment]
dont know what happened, but error is gone... thx!
