### ISSUE TITLE
support strlower for non-latin characters

### ISSUE THREAD

**Issue by Artur91425** [shagu/pfQuest#30]
function strlower only works for 0-127 ASCII characters. To make it work for other characters, need do the hook.
Proof:
**without a hook**
![bandicam 2017-11-17 20-40-21-672](https://user-images.githubusercontent.com/24303693/32960917-b8d4b788-cbd7-11e7-9638-2fda2d2b7c81.jpg)
no search result

**with a hook**
![bandicam 2017-11-17 20-41-05-186](https://user-images.githubusercontent.com/24303693/32960938-c3a1983e-cbd7-11e7-9688-148679afc4d9.jpg)

Here is an example of a hook (author @Shuraken007):

```
function chsize(char)
   if not char then
      return 0
   elseif char > 240 then
      return 4
   elseif char > 225 then
      return 3
   elseif char > 192 then
      return 2
   else
      return 1
   end
end

old_strlower = strlower

function strlower(str)
   if not str then return nil end
   local t
   str = gsub(str, ".[\128-\191]*",
      function(w)
         t = strlower_hook(w, chsize(strbyte(w)))
         return t or w
      end
   )
   return old_strlower(str)
end
	
function strlower_hook(word, byte_size)
	if byte_size == 2 then
		l_byte = strbyte(word, 1)
		r_byte = strbyte(word, 2)
		if "А" <= word and word <= "П" then
			return strchar(l_byte)..strchar(r_byte + 32)
			elseif "Р" <= word and word <= "Я" then
			return strchar(l_byte + 1)..strchar(r_byte - 32)
		end
	end
	return nil
end```

My search began to work slowly and began to slow down :( Can you have an idea how to make it work better and faster?

**Comment by shagu** [comment]
I don't really get what this is doing, is that only related for ruRU-clients?

**Comment by Lichery** [comment]
This problem applies to all symbols of ASCII tables after 127.
That is, this standard lua function will not work for all Cyrillic characters and for special characters of other languages. See 192-255 characters:
http://www.rapidtables.com/code/text/ascii-table.htm

**Comment by Road-block** [comment]
The solution is [UTF8](https://github.com/Road-block/Select_AddOns/raw/1.14/UTF8-1.1-11200.zip) either embedded or as an optional supporting addon that is used if present.  
It adds these utf8 aware methods
```
utf8len(s)
utf8sub(s, i, j)
utf8reverse(s)
utf8upper(s)
utf8lower(s)
``` 
to the string library.  
So by checking for `type(string.utf8upper)=="function"` etc you can use the utf8 aware methods on locales that need it.

**Comment by Shuraken007** [comment]
on practice the fastest replaces looks like
str = gsub(str, ".[\128-\191]*", function(w) return replace_table[w] or w
end)
as I remember 7 time acceleration

**Comment by shagu** [comment]
it works for me for umlauts like `ä,ö,ü`

![image](https://user-images.githubusercontent.com/11586807/40063861-88b3564a-585e-11e8-9180-f55e161df007.png)

Is there anyway how I could reproduce your issue?

**Comment by Lichery** [comment]
install ruRU database
Enter the "оберег удачи" (all lowercase characters) into the search field.
in the quests tab there will be no search results
But as soon as you enter the name with a capital character (Оберег удачи), then the quest will immediately be found.

P.S. Try to copy the words from here and paste in the game. If instead of characters there are question marks, then unsubscribe here, I'll try to think of something

**Comment by Lichery** [comment]
![bandicam 2018-05-15 18-08-16-819](https://user-images.githubusercontent.com/24303693/40065735-1baf8d54-586b-11e8-90c0-909ac980704d.jpg)
![bandicam 2018-05-15 18-08-24-198](https://user-images.githubusercontent.com/24303693/40065736-1bdf532c-586b-11e8-8970-89ac88736024.jpg)

**Comment by Lichery** [comment]
By the way you have incorrectly tested. The strlower does not work for special characters. In other words, to play a bug, you need to enter a word that starts with a special character (ä, ö, ü). I hope in your language there are such words, and also in the game there are items/objects/quests with such words.
For example, there is the word äpple (sorry, but I do not know your language and could not think of anything better :)) So, the game has the item "Äpple". If you enter "äpple" in the search bar, there will be no results. But if you enter a case-sensitive name ("Äpple"), then will be results.

I hope I clearly explained.

**Comment by shagu** [comment]
Ah, I see. Thanks

**Comment by shagu** [comment]
![image](https://user-images.githubusercontent.com/11586807/40107543-d2b3a6d8-58f8-11e8-9c32-d02216cc1acb.png)

**Comment by Lichery** [comment]
and now enter the "über" and you will not have results.

**Comment by shagu** [comment]
![image](https://user-images.githubusercontent.com/11586807/40134993-571067fe-5944-11e8-9605-a9847fab667d.png)

![image](https://user-images.githubusercontent.com/11586807/40135002-5bc65c18-5944-11e8-954a-c5ae079c340c.png)

German umlauts seem to be unrelated to this issue.

**Comment by Shuraken007** [comment]
As I understand you have some troubles with understanging, how utf8 works?
here is explain:
let's read first byte: you may encode all symbols in 0-256  interval
if byte \in [0:127] - it's standart ASCII symbol
if byte \in [192:223] - then read next byte; symbol = 2 bytes
if byte \in [224:239] - then read next 2 bytes; symbol = 3 bytes
if byte \in [240:244 ] - then read next 3 bytes; symbol = 4 bytes
Bytes     Byte 1    Byte 2     Byte 3     Byte 4
  1      0xxxxxxx
  2      110xxxxx 10xxxxxx
  3      1110xxxx 10xxxxxx 10xxxxxx
  4      11110xxx 10xxxxxx 10xxxxxx 10xxxxxx
All other bytes in that chain have interval [128; 191]
As you understand only extra bytes have interval [128; 191] - first byte can't have it.
so - that first example probably had some mistakes with intervals, but it was 
enough to work with Cyrillic.

You may print all symbols, reading string
`for w in string.gfind(s, ".[\128-\191]*") do
   print(w)
end`

the simplest and fastest method - make table of replaces( write it in .lua file with utf8 encoding)
(example for EU locale - it's senselessly to make it for EU - but ok for example)
replace_table = {
A = 'a',
B = 'b',
...
Z = 'z'
}
str = gsub(str, ".[\128-\191]*", function(w) 
   return replace_table[w] or w
end)
as you see if there aren't such replace - symbol itself will be returned
but whats about Chinese - it can have more, than 80.000 symbols
if you will check utf8 encoding symbols - you may notice that usually letters are in blocks
(this blocks have no relation to reality for latin, but russian symbol's location looks like this)
----Block1----
a, b, c, ..., l
----Block2----
m, n, ..., z
----Block3----
A, ..., L
----Block4----
M, ..., Z

so - you can write function which can logically correlate one blocks with other
as example for russian language next rule work:
(rus language encoding with 2 bytes)
if  'А'<= w <= 'П' then
   add to second byte 32:   'a'<=new_w<='п'
if 'Р'<=w<='Я' then
   add to first byte 1, substract from second byte 32:  'р'<=new_w<='я'

probably language have different length of symbols - and you should give to replace function size of symbol: you take first number in first byte - strbyte(w, 1), you may check it and understand length of symbol: 1-4 bytes, I made chsize function (probably you should fix intervals)

I think that common decision should looks like:

`old_strlower = strlower

function strlower(str)
   if not str then return nil end
   local t
   str = gsub(str, ".[\128-\191]*",
      function(w)
         return replace_func(w, chsize(strbyte(w))) or w
      end
   )
   return old_strlower(str)
end`

where replace_func(w, w_length) may return table:
`eu_table = {
A = 'a',
B = 'b',
...
Z = 'z'
}
function replace_func(w, w_length)
   return eu_table[w]
end
`
or custom logics - using realization of language in utf8
first method with with table is the fastest
second method is slower, but probably better for really giant languages
