### ISSUE TITLE
Attaching the button to the minimap

### ISSUE THREAD

**Issue by Lichery** [shagu/pfQuest#32]
The button is not attached to the minimap...or it was planned?)
![bandicam 2017-11-18 22-12-51-195](https://user-images.githubusercontent.com/24303693/32983931-a989e498-ccad-11e7-87fe-1b92f5c1a14f.jpg)

**Comment by Lichery** [comment]
Please respond, if it does not, then I will suggest a code that supports the movement of the button for any kind of minimap

**Comment by shagu** [comment]
No, the user should be able to decide where to put it. But I'll add a description to the tooltip to make it clear that it's movable by shift-click.

**Comment by shagu** [comment]
Oops, you're right, another thing I should change... Sorry for confusion
