### ISSUE TITLE
v2.1 conflict with DPSMate

### ISSUE THREAD

**Issue by Road-block** [shagu/pfQuest#33]
`[2017/11/23 05:10:59-3753-x2]: pfQuest\pfMap.lua:132: attempt to index a nil value
pfQuest\pfMap.lua:132: in function <Interface\AddOns\pfQuest\pfMap.lua:130>
<in C code>: in function `SetPlayerBuff'
DPSMate\DPSMate_Options.lua:848: in function `PopUpAccept'
<string>:"DPSMate_PopUp_Total:OnClick":2: in main chunk

  ---`

This happens when accepting the reset of DPSMate data from it's options popup.  
The reason is DPSMate is using GameTooltip as a buff scanner (sets buffs on it and parses the text).  
pfQuest on the other hand creates a child frame parented to GameTooltip (pfMap.tooltip) which shows with the GameTooltip.  
When the GameTooltip is used as a buff scanner there no guaranteed `GetMouseFocus()` frame under it.

**Comment by shagu** [comment]
https://github.com/shagu/pfQuest/commit/4d8005afbeb59860fedefbb527c2eb7fa959d44f
