### ISSUE TITLE
Massive frame stutters when addon is enabled

### ISSUE THREAD

**Issue by kodikun** [shagu/pfQuest#35]
Not sure what conflict could be causing this, but if I enable this addon I get massive frame stutters periodically while playing. I have my addon memory usage uncapped (I thought that might fix it, but to no avail) and I'm not sure what else to do other than keep the addon disabled. Which is a shame because I really like it!

**Comment by nerdinja** [comment]
Having the same issue as @kodikun -- I'm wondering why you closed this issue? Did you find a fix, or just stop using pfQuest/Questie?

**Comment by shagu** [comment]
@nerdinja did you installed the latest version?

**Comment by kodikun** [comment]
I closed the ticket because I found the issue, and it wasn't with pfQuest. The problem was with DPSMate.
