### ISSUE TITLE
Support for manually completing quest

### ISSUE THREAD

**Issue by mattym00cow** [shagu/pfQuest#36]
It would be really fantastic if this addon supported a mechanism to mark quests as already completed. That way, I could utilise the functionality that shows uncompleted quests without my map being cluttered from all the quests I had completed before I got the addon.

**Comment by shagu** [comment]
You can use Shift-Click, but for nodes with multiple entries, this will always remove the topmost.

**Comment by Lichery** [comment]
he means a request from the server about the quests completed)

**Comment by mattym00cow** [comment]
That would be the dream but from what I can tell, the API for accessing this information wasn't exposed till tbc.

**Comment by shagu** [comment]
* Shift-Click to remove completed quests does already exist
* Querying the server for completed quest is not possible

Can I close this issue or ist there still anything open?

**Comment by mattym00cow** [comment]
Yeah go for it. Your initial response was great. Thanks!
