### ISSUE TITLE
Problem with ruRU localization

### ISSUE THREAD

**Issue by Oshire** [shagu/pfQuest#37]
HI there! Just after i log in i got this message in chat window. I am using the latest version of PFquest (2.1.1 atm) from release page.

![screen shot 2017-12-05 at 16 34 17](https://user-images.githubusercontent.com/34275131/33609838-b1493302-d9da-11e7-83cb-02016b5bda86.png)

**Comment by shagu** [comment]
It looks like the version you downloaded does not match the client you're using. Do only use the ruRU version if you're running a ruRU-localized gameclient.

**Comment by Lichery** [comment]
No, an error due to something else. If use a version that does not match the client, then just quests will not be shown, there were no errors.

**Comment by Lichery** [comment]
I tested different variants and there were never errors

**Comment by shagu** [comment]
because youre using the master version with all databases included. This error is because the addon tries to access a database which is not present.

**Comment by Oshire** [comment]
@shagu Yes it appears that this is the case. Not a big deal though, probably i messed up my localization. Thank you for your answer. Case Closed.

**Comment by Lichery** [comment]
@shagu I'm using the release version. English Client + ruRU Addon and I do not have an error
