### ISSUE TITLE
Combine zone databases

### ISSUE THREAD

**Issue by Lichery** [shagu/pfQuest#38]
please combine the database of zones. something like that [zones.zip](https://github.com/shagu/pfQuest/files/1532820/zones.zip) and put this pfQuest\db

Because as I wrote earlier, many servers do not have Russian server localization and if quests in English, need to download the version of enUS. But in this version there is a database with enUS zones (!) And because of this the addon does not work on the Russian client ... :((( It is necessary manually to transfer the base of zones from the Russian version to the English databases. Of course, I can do this without problems, but it will be difficult for most ordinary users.

I already posted your addon for download on our [site](https://wowruru.github.io/addons/pfQuest) (team WoWruRU), because this addon very good. :) But once again I repeat that Russian players will have the problem described above (if the server does not have Russian localization)

**Comment by shagu** [comment]
I know.. I know...

**Comment by shagu** [comment]
A new download target has been added, called `noLoc`. Choose this if you are playing with a localized client (e.g ruRU) on a server that doesn't ship any translations (e.g kronos). The non-localized pfQuest download contains a complete enUS database plus the localized zone databases for every language.
