### ISSUE TITLE
Blindweed tracking, hard to see

### ISSUE THREAD

**Issue by olepg** [shagu/pfQuest#40]
Hi.

I'm currently farming blindweed, and I find them very hard to see.
Both on the minimap and the big map: https://i.imgur.com/D22RbCR.png

Can the colors of Blindweed dots be changed to something with more contrast to the background?

**Comment by shagu** [comment]
Click on the dot and it will change its color ;)

**Comment by olepg** [comment]
Wow nice! Great.
