### ISSUE TITLE
Error when logging in to fresh character

### ISSUE THREAD

**Issue by Muehe** [shagu/pfQuest#41]
![screenshot_2017-12-22_16-45-32](https://user-images.githubusercontent.com/8838573/34303980-10cb7294-e738-11e7-8d59-ab061213d053.png)

Seems like pfQuest is trying to scan the empty quest log.

**Comment by shagu** [comment]
Thanks man
https://github.com/shagu/pfQuest/commit/b814bd800f742844215e242c0fbb6fc589e8fb65
