### ISSUE TITLE
Quest chains [ruRU]

### ISSUE THREAD

**Issue by M2us** [shagu/pfQuest#42]
When I take this quest [[Panther Mastery]](http://wowroad.info/?quest=190) marker set not on [Young Panther](http://wowroad.info/?npc=683), addon think I take this quest [[Panther Mastery]](http://wowroad.info/?quest=193) and set marker on [Bhag'thera](http://wowroad.info/?npc=728).

Some quests chains like this have too this problem. Sometimes marker set on last quest, sometimes to middle quest. But some quests chains work perfectly.

I compared addon text with quest, it matches.

**Comment by Muehe** [comment]
I already made Shagu aware of this problem. It basically effects every quest which is a chain with the same quest name and where the first 10 characters of their objective text are the same (this is how the lookup works in pfQuest right now). The problem can be significantly reduced by using the full objective text and even further by using other data (like race, class, relation to other quests) but it requires the DB to be completely reformatted and expanded. So a fix might take some time...

**Comment by M2us** [comment]
I see.
So, this problem is not only on the ruRU version...

**Comment by shagu** [comment]
This should be fixed in the latest `master` version. But there is no official release yet.
