### ISSUE TITLE
Suggestion: Option to hide Minimap Button.

### ISSUE THREAD

**Issue by dogmax** [shagu/pfQuest#43]
I really want to use pfQuest, but it conflicts with the way my UI looks and I want to hide the minimap button. Would this be a possible feature?

**Comment by cralor** [comment]
I'd like to see this too.

**Comment by shagu** [comment]
Fixed on latest `master`. There is no release yet.

https://github.com/shagu/pfQuest/commit/5dedb7ad5c1a2300cef478d6a3730ae7b6821fe5
