### ISSUE TITLE
Reccurent reload

### ISSUE THREAD

**Issue by 7h3Cub3** [shagu/pfQuest#45]
Hello,

with pfquest and even with no other addons loaded (deleted all cache/config and so on) about every 30sec the interface reload freezing up the game for a few seconds, in a cycle, has anyone encountered this ? i play with wow vanilla 1.12 client.

Thanks.

**Comment by shagu** [comment]
Should be fixed on the latest `master` version. There is no release yet, but feel free to beta-test.
