### ISSUE TITLE
Linking Quests In Chat Not Working

### ISSUE THREAD

**Issue by ktron3393** [shagu/pfQuest#49]
Hey, there seems to be something wrong with linking quests in chat. When i shft+click on a quest to link it in chat the link shows up in the my type box, but when i hit enter nothing shows up. Not even just the quest in brackets without it being an actual link. 

I have other addons running, but ive isolated it to pfQuest by turning all the other addons off except for pfQuest. I tried deleting my WTF folder and redownloading pfQuest and neither of these fixed it.

**Comment by shagu** [comment]
Hi,
There aren't any real questlinks in vanilla and kronos doesnt allow colored text in chat. 
That's why pfQuest can't emulate them.

**Comment by burner1024** [comment]
But is it possible to have non-colored links?

**Comment by shagu** [comment]
> But is it possible to have non-colored links?

No, both color and the link itself are usually blocked. But there is an option called "Enable Quest Link Support", you can disable it, to at least be able to paste the quest title.

**Comment by burner1024** [comment]
I see, too bad. Thank you.
