### ISSUE TITLE
Feature Request: Hide individual quests from the world map+minimap.

### ISSUE THREAD

**Issue by dogmax** [shagu/pfQuest#50]
Description of feature: 
pfQuest adds 3 red buttons in the questlog. "Show", "Clean" and "Reset". I suggest adding a 4th button labelled "Hide" - or something similar. The function of the button: Hide the elements related to that specific quest from the world and mini map. 

Issues that it solves: 
Sometimes you get a quest where a lot of mobs across the world have a very low chance to drop a specific item. This clutters the map with little dots for every NPC or interactive object that is related to the quest. The clutter can sometimes be some extensive that it is nigh impossible for the user to find relevant information about other quests.

**Comment by Muehe** [comment]
Assuming you have the little box on the world map set to "All Quests" rather than "Tracked Quests" or "Manual Selection", wouldn't it be better to implement a "minimum drop chance" setting? I.e. set it to 5 and everything with a drop-chance less than 5% is not shown anymore.

**Comment by dogmax** [comment]
I was considering that but it doesnt solve a lot of quests.

There are many quests where it's not drop chance related because they are pick-up quests or require you to interect with world objects that are scattered around the map. These objects would not be affected.


There is also the situation where there are multiple quests in a very tight and small spot where it would be beneficial to the user to be able to switch between hidden and shown states directly from the quest log. Why? Because they can view the change directly on the minimap instead of having to open the world map.

**Comment by shagu** [comment]
Fixed on the latest `master`. Feel free to beta-test. :)
