### ISSUE TITLE
[2.99 Alpha] browser: bug with list scrolling

### ISSUE THREAD

**Issue by Lichery** [shagu/pfQuest#55]
I can scroll the empty list down to infinity. This bug appears when you type "mons"
![bandicam 2018-05-04 22-48-16-028](https://user-images.githubusercontent.com/24303693/39649335-29bd182e-4fee-11e8-8e34-ad104b53126d.jpg)

**Comment by shagu** [comment]
Thank you :) I will have a look

**Comment by shagu** [comment]
https://github.com/shagu/pfQuest/commit/726ad89dfe6eade3241a65ba8f0967e41869b976
