### ISSUE TITLE
QuestLog: add IDs for accepted quests

### ISSUE THREAD

**Issue by Lichery** [shagu/pfQuest#56]
something like that:
![bandicam 2018-05-04 23-02-53-129](https://user-images.githubusercontent.com/24303693/39650142-af3402fa-4fef-11e8-958c-b846f2c1ef03.jpg)

**Comment by shagu** [comment]
https://github.com/shagu/pfQuest/commit/9b225494d42309a3eb7301d8617523f5d47271f3

![questid](https://user-images.githubusercontent.com/11586807/39665289-9a3abf68-5091-11e8-82c5-0e401dacd363.gif)
