### ISSUE TITLE
NPC tooltip: row repeat

### ISSUE THREAD

**Issue by Lichery** [shagu/pfQuest#59]
![bandicam 2018-05-10 18-54-47-724](https://user-images.githubusercontent.com/24303693/39879527-b663d364-5483-11e8-889b-46a14439ef41.jpg)

**Comment by shagu** [comment]
Is it the latest master branch? I've pushed alot of stuff yesterday

**Comment by Lichery** [comment]
Yes, sorry, forgot to write. This is the latest version, downloaded literally a couple of hours ago.

**Comment by Lichery** [comment]
enUS version. Tested on enUS game client.

**Comment by shagu** [comment]
Thanks, I will check

**Comment by Lichery** [comment]
after loot [Gallywix's Head](http://classicdb.ch/?item=8074):
![bandicam 2018-05-10 23-02-10-432](https://user-images.githubusercontent.com/24303693/39891479-649f40fe-54a6-11e8-9e00-e959e9c60596.jpg)

**Comment by Lichery** [comment]
Also here's another problem. I just can not understand at what point it appears. These mobs are at the bottom of the tower and I always kill 2 of them, but then after a while start to write 1/2
![bandicam 2018-05-10 23-05-19-066](https://user-images.githubusercontent.com/24303693/39891727-0a270cbe-54a7-11e8-81e2-41f3f40bf2f8.jpg)
after restarting the game writes correctly

**Comment by Lichery** [comment]
after looted Gallywix's Head begins to write 1/2

**Comment by shagu** [comment]
Quest: 2478
https://classicdb.ch/?quest=2478

Item: 8073
https://classicdb.ch/?item=8073

**Comment by shagu** [comment]
https://github.com/shagu/pfQuest/commit/aaf97ad7f60355f97d16f921cf4dbd0e61c99c43

**Comment by shagu** [comment]
Regarding the 1/2 Quest-text entry, that's nothing that pfQuest has to do with.
