### ISSUE TITLE
Querying ingame 

### ISSUE THREAD

**Issue by CodyBontecou** [shagu/pfQuest#62]
I'm hoping to do something like `/db query location=winterspring object=chest`, telling me which chests are in winterspring. 

Data I could later use on something like: `/db object Solid Chest` 

Is this possible?

**Comment by shagu** [comment]
what's wrong with `/db meta chests` ?

**Comment by CodyBontecou** [comment]
What should I expect from that? I'm not seeing any change from it.

**Comment by shagu** [comment]
It displays all chests on the worldmap

**Comment by CodyBontecou** [comment]
You know what turns out I'm on the wrong version. Thanks.
