### ISSUE TITLE
in zhCN Client. Unable to display Quests of the Horde City

### ISSUE THREAD

**Issue by Qcat0214** [shagu/pfQuest#63]
hey shagu dear.
in ur latest version. 
for example.I'm a Horde character.I can not see the task of thunder cliff on the map of the worldmap.
But if I'm a Alliance character .I can see all quests of Alliance Citys.
The old version(2.99-alpha) is without this problem

**Comment by shagu** [comment]
Hi,

I don't understand. For me, as a Tauren I can see Horde quests. And as a Nightelf, I can see Alliance quests. Please provide more information

**Comment by Qcat0214** [comment]
well, I mean.as a orc I can not see Orgrimmar quests. as a Tauren I can not see Thunder Bluff quests. and as a undead I can not see Undercity quests.
But if as a Human. I can see  Storm City.ironforge.and Darnassus quests.
