### ISSUE TITLE
Nodes don't work on World Map, nodes show but nothing when hovered over

### ISSUE THREAD

**Issue by nectarines** [shagu/pfQuest#8]
Open World Map, I see nodes for my quests.  I hover over said nodes with mouse, nothing.

I open Quest Log, I select a quest and click "Show" --> World Map opens and I see nodes, I can now over over nodes and see the tooltips.

BUT, when I close the World Map again, and re-open, I see the nodes still, but once again does nothing when hovered over.

I tested every pfQuest release, and all of them had the same issue.  Please help, I love ShaguQuest so much, wanted to try this for a new Vanilla server.

**Comment by shagu** [comment]
Thank you, this will be fixed with the next Release: https://github.com/shagu/pfQuest/commit/737ca36bc74cb648dc7a5af3ea5cc0c3314aa231
