### ISSUE TITLE
localisation

### ISSUE THREAD

**Issue by shikulja** [shagu/pfQuest#86]
1. expand settings menu (I know the window is compact and looks good, but the text does not fit)
maybe there is an auto-alignment, I don't know
![Аннотация 2020-08-26 145142](https://user-images.githubusercontent.com/3386359/91300279-b0cefb00-e7ab-11ea-8814-51aa69c786e9.png)

2.  Browser: 
- Location Level Units Objects Items Quests - available in translation file, but only for hints
![Аннотация 2020-08-26 145359](https://user-images.githubusercontent.com/3386359/91300855-a4976d80-e7ac-11ea-9625-e8a7ff8beabf.png)

-world map - Unit available in translation file but not used
![Аннотация 2020-08-26 151257](https://user-images.githubusercontent.com/3386359/91302386-1670b680-e7af-11ea-8146-f869ec5c4ddc.png)

3. pfQuest: Journal
- Journal - available in translation file, but the title is not translated
![Аннотация 2020-08-26 145952](https://user-images.githubusercontent.com/3386359/91300966-d3154880-e7ac-11ea-9e61-ba4e2b7b9db5.png)

4. map tracker
![Аннотация 2020-08-26 150134](https://user-images.githubusercontent.com/3386359/91301104-0eb01280-e7ad-11ea-935f-ba0432c011a0.png)
- need add Distance to translation file

5. quest log
- need add all tooltips to translation file
![Аннотация 2020-08-26 150502](https://user-images.githubusercontent.com/3386359/91301408-8bdb8780-e7ad-11ea-9360-464aaf88ef81.png)
![Аннотация 2020-08-26 150440](https://user-images.githubusercontent.com/3386359/91301376-7cf4d500-e7ad-11ea-9154-63bef423f468.png)

- and control tips in the quest log
![Аннотация 2020-08-26 150547](https://user-images.githubusercontent.com/3386359/91301570-ce9d5f80-e7ad-11ea-9c68-7dfcf39da546.png)
![Аннотация 2020-08-26 152320](https://user-images.githubusercontent.com/3386359/91303060-21781680-e7b0-11ea-8b02-0fd55eef4b4f.png)

**Comment by shagu** [comment]
1. Make your text fit the window. There is always a way to rephrase something to make it fit.
I will add something to dynamically resize the window. But please review your texts and try to shorten them.
It was the same with the pfUI translation once ago, but in the end, everyone was able to phrase it in a way it fits.
https://github.com/shagu/pfQuest/commit/f77d610cb2065f0090cc6edf9ca71f3e5cb08983

2-5. I will add those.

**Comment by Artur91425** [comment]
You can also use "\n" to break a long line.  For example, "пример\nпереноса"

**Comment by shagu** [comment]
> You can also use "\n" to break a long line. For example, "пример\nпереноса"

No please don't. I'm not going to introduce dynamic heights.

**Comment by shikulja** [comment]
much better, even there is free space
I used the most understandable and convenient language for the players,
if you use abbreviations, they can only be like this:
Use - Использовать - Исп.
Enable - Включить - Вкл.
Others, for example: there is no way to shorten without complicating understanding, it will not be possible to find other words
["Include Unified Quest Locations"] = "Включая объединенные локации заданий", 
["Unified Quest Location Markers"] = "Объединенные маркеры местонахождения заданий",
![Аннотация 2020-08-26 160306](https://user-images.githubusercontent.com/3386359/91306750-a6b1fa00-e7b5-11ea-98d7-98401225b8cf.png)

**Comment by shikulja** [comment]
to make menus smaller, usually use tabbed menus, or as in pfui.
Perhaps when there are more settings, then it will be so

**Comment by shagu** [comment]
I don't speak your language, but I can't believe that things can't be rephrased and that you don't have synonyms in your language.
It does not have to be a 1:1 translations. E.g if "Enable Unified Nodes" is to large, an idea would be to simply use "Unified Nodes" since a checkbox beside should make it obvious that it's about enabling/disabling a feature.

**Comment by shikulja** [comment]
@shagu good idea, I'll try to do this

**Comment by shagu** [comment]
https://github.com/shagu/pfQuest/commit/de3bcc872a9f2b3d2b0dfd400fe27a43035b5fdc
