### ISSUE TITLE
index is nil

### ISSUE THREAD

**Issue by Artur91425** [shagu/pfQuest#89]
https://github.com/shagu/pfQuest/blob/557f2b429550467c2867032e374f135d2b9cadde/database.lua#L198

On the ruRU client. enUS does not raise this error. Loaded only pfQuest (latest). Inside the addon I have databases for ruRU and enUS.
![Capture](https://user-images.githubusercontent.com/24303693/91334926-5dbf6d00-e7d8-11ea-9c01-d51519da44e3.PNG)

**Comment by shagu** [comment]
I'm unable to reproduce. Using:
- 1.12.1 Client (ruRU)
- 5.0.1 pfQuest (ruRU)

**Comment by Artur91425** [comment]
i am using 1.12.1 ruRU client and pfQuest 5.0.2 (include ruRU and enUS databases), but i am running on my local server on account with admin level = 3. GM mode disabled. Perhaps it somehow affects ... Now I will try on some other server.
![image](https://user-images.githubusercontent.com/24303693/91337228-ba705700-e7db-11ea-8644-4b06e4d5b248.png)

**Comment by Artur91425** [comment]
On the https://elysium-project.org/howtoplay/en is the same ...

**Comment by Artur91425** [comment]
It does not find the "ruRU" key in the pfDB["items"] table

**Comment by Artur91425** [comment]
omg... sorry i think i understand what's the problem... just a moment

**Comment by Artur91425** [comment]
Everything is fine, sorry, I broke it myself and did not understand it right away. Initially, I downloaded the enUS version and then decided to download ruRU. In the end, I just inserted the ruRU folder, thinking that all the files are registered in .toc.
