### ISSUE TITLE
location of quests on the border of two locations // route repaint

### ISSUE THREAD

**Issue by Artur91425** [shagu/pfQuest#90]
Sorry for two bugs in one Issue. Both were recorded in one video and i decided not to duplicate.

1) Bug with the location of quest givers. They should be in the Tirisfal Glades zone or somehow try to implement two zones
2) The route is updated only from the second opening of the map

https://youtu.be/rY1EKMPH-78

**Comment by shagu** [comment]
![image](https://user-images.githubusercontent.com/11586807/91341250-83994180-e7d9-11ea-8131-5428526f9c14.png)

**Comment by Artur91425** [comment]
Try it now

**Comment by shagu** [comment]
Seems to only happen without pfUI :thinking:

**Comment by shagu** [comment]
Both fixed, thanks for your report :+1: 
https://github.com/shagu/pfQuest/commit/14a0041f386284b83fd71e11efcd69f45b622848
