### ISSUE TITLE
Hiding the cluster does not work when holding Ctrl

### ISSUE THREAD

**Issue by Artur91425** [shagu/pfQuest#91]
Loaded only pfQuest 5.0.2. When I hold down Ctrl and move the mouse over the cluster, nothing happens, the same thing happens when I first move the mouse over the cluster and then hold down Ctrl

**Comment by Artur91425** [comment]
In the absence of pfUI, many problems arise.

I just noticed a couple more bugs:
1) The fading of inactive nodes does not work when you hover the mouse over the world map
2) if you hover the mouse over a node on the minimap and open the world map in this state, the nodes that have faded on the minimap will be displayed on the world map with the same fading

**Comment by shagu** [comment]
Interesting :thinking: 
The default fullscreen map of wow, completely hides the UIParent frame. 
I didn't knew that :smile: 

The map is no re-anchored from UIParent to WorldFrame to no longer get hidden by fullscreen elements.
https://github.com/shagu/pfQuest/commit/6fbfa2cd0e1670bc2c37b698d0452109eeaf8c45

**Comment by Artur91425** [comment]
> 
> 
> Interesting 🤔
> The default fullscreen map of wow, completely hides the UIParent frame.
> I didn't knew that 😄
> 
> The map is now re-anchored from UIParent to WorldFrame to no longer get hidden by fullscreen elements,
> in order to proceed with its update handlers: [6fbfa2c](https://github.com/shagu/pfQuest/commit/6fbfa2cd0e1670bc2c37b698d0452109eeaf8c45)

This fixed all the bugs) Thanks!
