### ISSUE TITLE
Game slowdown

### ISSUE THREAD

**Issue by nonameform** [shagu/pfQuest#97]
I have noticed that if you enable extra nodes (eg. mines) and have a **world map opened** and then hover over a node on the **minimap** FPS drops around 50% for a brief moment. That does not happen consistently, but once that happens, it will continue that way.

**Comment by nonameform** [comment]
Scratch that. If you have world map opened and then hover over any node on the minimap while moving (even happens with quest nodes), the game might slowdown.

https://youtu.be/Cp8hhG5BN6I

**Comment by shagu** [comment]
I can add an option to disable map animations if you want.

**Comment by nonameform** [comment]
I believe if there is no demand for that feature so far, maybe it is better to invest your time in something else :)
