### ISSUE TITLE
extractor: support multiple quest requirements

### ISSUE THREAD

**Issue by nonameform** [shagu/pfQuest#98]
Where do I report wrong quest requirements? Sometimes pfQuest will show that a quest is available, but the NPC will not offer one as it is a part of a chain that requires you to finish other quests first. For example, _An OOX of Your Own_ requires you to finish three escort quests in Tanaris, The Hinterlands and Feralas, but once I hit level 40 pfQuest shows the quest in Booty Bay as available for taking.

**Comment by nonameform** [comment]
Do I need to report the other quests one by one? There are quite a few like this.

**Comment by shagu** [comment]
No, it seems to be a problem in general. Actually two.
All Quests with multiple quest requirements to do not show up correctly:

1. The pfQuest extractor does only support one dependency per quest.
2. For quests with mutliple requirements, the VMaNGOS database does not show dependency as I used to crawl them.

The extractor requires some rework here. Thanks for your report.

An OOX of Your Own [id: 3721]
https://classicdb.ch/?quest=3721

```sql
select PrevQuestId from quest_template where entry = 3721
=> 0
```

Should have: 648, 836, 2767

Maybe another table or row is used to determine dependencies in VMaNGOS.

**Comment by nonameform** [comment]
I wonder if it the same issue with _The Mithril Order_ (2760). I saw the quest at level 40, but it requires you to either do Horde or Alliance pre-requrements before it is available. And sometimes as Alliance character I see Horde quests.

**Comment by shagu** [comment]
The entries show that there is no requirement listed (a ["pre"]-field) for the quest "2760" in db/quests.lua.
I assume it's the same issue. I probably don't scan the proper database field to determine quest requirements on vmangos/cmangos.

**Comment by shagu** [comment]
Fixed by https://github.com/shagu/pfQuest/commit/bae7b66e313f7b9eef20e7c9aa8fd873bb82eb19 (5.2.4)
